from pathlib import Path
root=Path('/mnt/data/tbm_next/src')
logo='https://raw.githubusercontent.com/Ateeqqqq/thebuzzmedia-assets/refs/heads/main/logo.png-Photoroom.png'
footer=f'''<footer class="about-footer service-footer social-footer"><div class="about-footer-brand"><img src="{logo}" alt="The Buzz Media"><p>Digital experiences, marketing systems, software and AI solutions for ambitious brands.</p><a href="tel:+919182041323">+91 91820 41323</a><a href="mailto:hello.thebuzzmedia@gmail.com">hello.thebuzzmedia@gmail.com</a></div><div class="about-footer-map"><iframe title="The Buzz Media location" src="https://www.google.com/maps?q=Pillar%20No.%20209%2C%20MQ%20Splendor%2C%20Upperpally%2C%20Hyderabad%2C%20Telangana%20500048&output=embed" loading="lazy" referrerpolicy="no-referrer-when-downgrade"></iframe></div><div class="about-footer-bottom"><span>© 2026 The Buzz Media. All rights reserved.</span><span>Hyderabad, India</span></div></footer>'''
menu='''<div class="service-nav-dropdown"><button class="service-dropdown-trigger" type="button">Services <span>⌄</span></button><div class="service-dropdown-menu"><a href="#performance-marketing">Performance Marketing</a><a href="#social-media-marketing">Social Media Marketing</a><a href="#seo">SEO</a><a href="#app-development">App Development</a><a href="#digital-marketing">Digital Marketing</a><a href="#website-development">Website Development</a><a href="#erp-business-software">ERP &amp; Business Software</a><a href="#graphic-designing">Graphic Designing</a><a href="#aeo">AEO</a><a href="#geo">GEO</a></div></div>'''
header=lambda active: f'''<header class="main-header hero-header social-header"><a href="#home" class="header-logo" aria-label="The Buzz Media home"><img src="{logo}" alt="The Buzz Media" class="header-logo-image" /></a><nav class="main-nav" aria-label="Main navigation"><a href="#home">Home</a>{menu}<a href="#about">About Us</a><a href="#careers">Careers</a><a href="#clients">Clients</a><a href="#contact">Contact Us</a></nav><div class="header-right"><button class="header-circle theme-button" type="button" aria-label="Theme">☾</button><a href="https://www.facebook.com/people/Thebuzzmedia/61592806665911/" target="_blank" rel="noopener noreferrer">f</a><a href="https://www.instagram.com/thebuzzmediaco/" target="_blank" rel="noopener noreferrer">◎</a><a href="https://www.linkedin.com/company/thebuzzzmedia/" target="_blank" rel="noopener noreferrer">in</a><a href="https://docs.google.com/forms/d/e/1FAIpQLScD7N0CLzOaXmmMoNnJAP18Aub78K1O5hOanYXn--QNpZVUuQ/viewform?pli=1" target="_blank" rel="noopener noreferrer">✦</a><button class="header-circle menu-button" type="button" aria-label="Menu"><span>•••</span><span>•••</span><span>•••</span></button></div></header>'''

pages={
'graphic':{
'file':'graphicDesigningContent.js','hash':'graphic-designing','name':'Graphics & Content','kicker':'GRAPHICS & CONTENT DESIGN','hero':'Elevate Your Brand with <span>Graphic Design</span>.','intro':'Turn your visual identity into a consistent, recognizable brand system with design that works across every touchpoint.','cards':[('Graphic Design','Create striking visuals that capture your brand identity and communicate clearly.','VISUAL IDENTITY'),('Content Writing','Develop high-quality copy and content that gives your brand a sharper voice.','CONTENT'),('Branding Solutions','Build a cohesive brand identity through professional logos and strategic creative direction.','BRANDING'),('Visual Storytelling','Combine design and narrative to make campaigns memorable and engaging.','CAMPAIGNS'),('SEO Content Optimization','Make content useful, readable and discoverable across search and AI discovery.','CONTENT SEO')],
'ecosystem':'Explore Our Graphics & Content Toolkit','tools':['Figma','Adobe Photoshop','Illustrator','Canva','After Effects','Premiere Pro','CapCut','Notion'],
'expertise':'Expertise for your Graphics & Content Success.','expertcopy':'We combine visual craft, brand thinking and content strategy to create a consistent system your audience can recognize and remember.','list':[('Experienced Designers','Purposeful visual systems built around your brand personality and audience.'),('Consistent Content','Clear creative direction across social, web, campaigns and everyday communication.'),('Creativity Meets Strategy','Design choices tied to business goals, not decoration for decoration’s sake.')],
'process':'Our proven process for creative work.','steps':[('Discover','Understand the brand, audience and creative challenge.'),('Concept','Develop directions, references and a visual route.'),('Create','Design the assets, content and system with consistency.'),('Refine','Review, test and prepare everything for launch.')],
'leaders':'Leaders in Graphics & Content.','stats':[('70+','CREATIVE PROJECTS'),('8+','BRAND SYSTEMS'),('142+','DESIGN ASSETS')],
'faqtitle':'Everything You Need to Know About Graphics & Content','faqs':[('What types of graphics do you create?','Social posts, campaign creatives, brand assets, presentations, web visuals and more.'),('Do you offer content writing services?','Yes. We can develop brand-aligned copy for websites, campaigns and social content.'),('Can you help develop a content strategy?','Yes. We can map content pillars, formats and creative direction around your goals.'),('What is your process for graphic design projects?','We move from discovery and concept to design, review and final delivery.'),('How much does graphic design cost?','Pricing depends on scope, quantity, complexity and turnaround time.')],
'benefits':[('Custom Visuals','Purpose-built creative that fits your brand and audience.'),('Compelling Content','Clear messaging paired with visual consistency.'),('SEO-Optimized Content','Content designed for readability and discoverability.'),('Continuous Support','Ongoing creative support as your brand grows.')]
},
'website':{
'file':'websiteDevelopmentContent.js','hash':'website-development','name':'Website Development','kicker':'WEB DEVELOPMENT','hero':'Transformative Web Solutions by <span>The Buzz Media</span> to Boost Your Digital Presence.','intro':'Build a website that is fast, responsive, conversion-ready and designed around how your customers actually move.','cards':[('Website Design & Development','Crafting custom websites with modern design, intuitive interfaces and responsive layouts.','WEB DESIGN'),('E-Commerce Development','Build high-converting commerce experiences with scalable product and checkout flows.','COMMERCE'),('WordPress Development','Flexible WordPress builds for brands that need control, speed and a manageable CMS.','WORDPRESS'),('CMS Development','Create structured content management systems that make everyday updates simple.','CMS'),('Custom Web Application Development','Build focused web applications for unique workflows, portals and customer experiences.','WEB APPS'),('Website Maintenance','Keep your website secure, current, monitored and continuously improved.','SUPPORT')],
'ecosystem':'Explore Our Web Development Stack','tools':['React','Vite','Next.js','WordPress','Elementor','Tailwind CSS','FastAPI','MySQL','PostgreSQL'],
'expertise':'Expertise for Your Web Success.','expertcopy':'Our development process balances polished UX with reliable engineering, performance and maintainability so the website keeps working after launch.','list':[('Experienced Team','Designers and developers who work together from structure to deployment.'),('Tailored Solutions','We build around your business model, content and conversion goals.'),('Cutting-Edge Technology','Modern frameworks and tools chosen for performance, flexibility and scale.')],
'process':'Our proven process for web projects.','steps':[('Plan','Map pages, journeys, content and technical requirements.'),('Design','Create a clear visual system and responsive interface.'),('Build','Develop, integrate, test and optimize the experience.'),('Launch','Deploy, monitor and support the live product.')],
'leaders':'Leaders in Website Development.','stats':[('120+','DIGITAL PROJECTS'),('35+','BRANDS & CLIENTS'),('5+','YEARS OF PRACTICAL EXPERIENCE')],
'faqtitle':'Everything You Need to Know About Website Development','faqs':[('What platforms do you build websites with?','We work with React-based stacks, WordPress and custom web technologies depending on the project.'),('How long does it take to build a website?','Timelines depend on scope, content, integrations and revision cycles.'),('Do you provide website maintenance services?','Yes. We can provide ongoing updates, monitoring, fixes and improvements.'),('Can you build a custom web app?','Yes. We can build dashboards, portals and workflow-based applications.'),('How much does a website cost?','The price depends on pages, functionality, integrations and design complexity.')],
'benefits':[('Custom Solutions','Web experiences designed around your business.'),('Expert Team','A connected design and development workflow.'),('Data-Driven Insights','Performance and analytics built into the process.'),('Dedicated Support','Support and improvements beyond launch.')]
},
'aeo':{
'file':'aeoContent.js','hash':'aeo','name':'Answer Engine Optimization','kicker':'ANSWER ENGINE OPTIMIZATION','hero':'Dominate AI-Powered Search with <span>AEO</span> Strategies.','intro':'Structure your brand, pages and content so answer engines can understand, trust and surface your expertise.','cards':[('AI Answer Optimization','Make your content easy for answer engines to understand and retrieve.' ,'AI SEARCH'),('Structured Data & Schema Markup','Use structured signals to clarify entities, services, products and relationships.','SCHEMA'),('Content Formatting for AI','Create concise, well-structured answers that machines can parse and cite.','AI CONTENT'),('Featured Snippet Optimization','Shape useful answers for prominent search result formats.','SNIPPETS'),('Authority Building','Strengthen the trust signals around your brand, expertise and content.','AUTHORITY')],
'ecosystem':'The AEO Visibility Stack','tools':['Google Search','Google Business Profile','Schema.org','Search Console','Bing Webmaster Tools','GA4','FAQ Schema','Organization Schema'],
'expertise':'Mastering Answer Engine Optimization.','expertcopy':'AEO connects technical structure, useful content and authority signals so your brand can become easier for answer systems to understand and reference.','list':[('Proven Expertise','Content and structure designed around how answer engines retrieve information.'),('AI-First Approach','We format useful answers around intent, entities and clear supporting context.'),('Comprehensive Services','Technical, content and authority work combined into one discoverability system.')],
'process':'Our proven AEO process.','steps':[('Audit','Review technical, content and entity signals.'),('Structure','Build clear information architecture and schema.'),('Answer','Create useful, concise content around real questions.'),('Measure','Track visibility, citations and search behavior.')],
'leaders':'Leaders in Answer Engine Optimization.','stats':[('93+','CORE PAGES OPTIMIZED'),('37+','STRUCTURED CLIENTS'),('24/7','DISCOVERABILITY MINDSET')],
'faqtitle':'Everything You Need to Know About AEO','faqs':[('What is Answer Engine Optimization?','AEO is the practice of structuring content so answer engines can understand and surface useful responses.'),('How can AEO help increase online visibility?','Clear answers, strong entities and structured data can improve how your information is interpreted and discovered.'),('What are the key elements of AEO?','Useful content, semantic structure, schema, entity clarity, authority and technical accessibility.'),('How long does it take to see results with AEO?','Results vary by site authority, competition, content quality and implementation depth.'),('Which answer engines do you optimize for?','We can consider Google, Bing and emerging AI-powered discovery experiences.')],
'benefits':[('AI Answer Visibility','Make important information easier for answer systems to find.'),('Brand Authority','Strengthen the signals around your expertise.'),('Increased Discovery','Improve how your brand appears across modern search journeys.'),('Competitive Edge','Prepare your content for changing search behavior.')]
},
'geo':{
'file':'geoContent.js','hash':'geo','name':'Generative Engine Optimization','kicker':'GENERATIVE ENGINE OPTIMIZATION','hero':'Optimize for AI-Generated Content with <span>GEO</span> Strategies.','intro':'Prepare your brand and content for generative discovery across AI assistants and answer experiences.','cards':[('AI Content Generation Optimization','Create content that is useful, specific and easy for generative systems to interpret.','AI CONTENT'),('Semantic Content Optimization','Connect concepts, entities and context so generative systems understand your subject matter.','SEMANTICS'),('Contextual Content Markup','Provide the context and relationships AI systems need to interpret your content accurately.','CONTEXT'),('Multi-Modal Content Optimization','Align text, images and supporting media into a coherent information system.','MULTI-MODAL'),('Generative AI Training Data Optimization','Organize high-value brand information so it is consistent, accessible and useful across AI workflows.','AI DATA')],
'ecosystem':'The GEO Visibility Stack','tools':['Google AI Overviews','ChatGPT','Perplexity','Gemini','Copilot','Bing','Schema.org','Knowledge Graphs'],
'expertise':'Mastering Generative Engine Optimization.','expertcopy':'GEO focuses on the information systems behind AI discovery: context, entities, consistency, useful answers and strong source material.','list':[('Proven Expertise','Build content systems that communicate your expertise clearly to generative engines.'),('AI-First Strategies','Organize information around intent, entities and context instead of keyword stuffing.'),('Comprehensive Services','Technical, content and brand signals working together for AI discovery.')],
'process':'Our proven GEO process.','steps':[('Map','Identify entities, topics and brand knowledge.'),('Structure','Organize content and supporting evidence.'),('Publish','Create useful, source-ready information.'),('Measure','Review AI visibility and refine the knowledge system.')],
'leaders':'Leaders in Generative Engine Optimization.','stats':[('84+','CONTENT SYSTEMS'),('33+','SATISFIED CLIENTS'),('8+','AI DISCOVERY CHANNELS')],
'faqtitle':'Everything You Need to Know About GEO','faqs':[('What is Generative Engine Optimization?','GEO is the practice of improving how a brand and its information can be understood and surfaced by generative AI systems.'),('How can GEO help increase my online visibility?','It creates clearer, more useful information for AI-driven discovery and answer experiences.'),('What are the key elements of GEO?','Entity clarity, context, source quality, semantic structure and useful content.'),('How long does it take to see results with GEO?','There is no fixed timeline. Results depend on the quality, authority and consistency of the information system.'),('Which generative engines do you optimize for?','We can build for major AI discovery environments including ChatGPT, Gemini, Perplexity and Copilot.')],
'benefits':[('AI-Generated Content Visibility','Make useful brand information easier for AI systems to interpret.'),('Semantic Authority','Connect your expertise across topics, entities and content.'),('Increased Traffic','Improve discovery across emerging AI-assisted journeys.'),('Competitive Edge','Build a foundation for the next generation of search.')]
},
'erpbiz':{
'file':'erpBusinessContent.js','hash':'erp-business-software','name':'ERP & Business Software','kicker':'ERP & BUSINESS SOFTWARE','hero':'Connect Your Business with <span>ERP & Custom Software</span>.','intro':'Replace disconnected spreadsheets and manual handoffs with software that connects inventory, sales, purchasing, operations, teams and reporting.','cards':[('ERP Development','Design a central system for inventory, purchasing, sales, finance and operations.','ERP SYSTEMS'),('Inventory & Stock Management','Track branch-wise stock, transfers, variants, reservations and movement in real time.','INVENTORY'),('Sales & Order Workflows','Connect quotation, confirmation, reservation, purchasing, delivery and payment flows.','SALES OPS'),('Custom Business Software','Build internal tools, portals and workflows around the way your business actually operates.','CUSTOM SOFTWARE'),('Dashboards & Reporting','Turn operational data into role-based dashboards and actionable reports.','ANALYTICS'),('Automation & Integrations','Connect WhatsApp, payments, courier tools, accounting systems and APIs to reduce manual work.','AUTOMATION')],
'ecosystem':'The Business Systems Stack','tools':['React','FastAPI','PostgreSQL','MySQL','REST APIs','WhatsApp API','Razorpay','Cloud Hosting','Role-Based Access'],
'expertise':'Business Software Built Around Your Workflow.','expertcopy':'Instead of forcing your operation into a generic product, we map your real workflow first and then design the software around the people, data and decisions that keep the business moving.','list':[('Workflow-First Discovery','We map branches, roles, stock, approvals, documents and handoffs before development.'),('Modular Architecture','Start with the workflows that matter most and expand the system as the business grows.'),('Real-Time Visibility','Give owners and teams one reliable view of operations, inventory and performance.')],
'process':'Our proven software process.','steps':[('Map','Document workflows, roles, data and exceptions.'),('Architect','Design the database, modules, permissions and integrations.'),('Build','Develop the web/mobile interfaces and business logic.'),('Deploy','Test, train, launch and continuously improve the system.')],
'leaders':'Software That Understands Your Business.','stats':[('1','CENTRAL PLATFORM'),('24/7','DATA ACCESS'),('100%','WORKFLOW FOCUS')],
'faqtitle':'Everything You Need to Know About ERP & Business Software','faqs':[('Can you build a custom ERP for our business?','Yes. We can design modules around your actual inventory, sales, purchasing, operations and reporting workflows.'),('Can ERP support multiple branches?','Yes. Branch-wise roles, stock, transfers and reporting can be designed into the system.'),('Can you integrate existing tools?','Yes. APIs can connect payments, messaging, courier services, accounting tools and other systems.'),('Can you build a mobile app with the ERP?','Yes. A web application and Android/mobile experience can share the same central database and business logic.'),('How do you price custom software?','Pricing depends on modules, integrations, user roles, mobile requirements and project complexity.')],
'benefits':[('One Source of Truth','Centralize operational data instead of scattered spreadsheets.'),('Workflow Automation','Reduce repetitive manual work and approval delays.'),('Scalable Architecture','Start focused and add modules as the business grows.'),('Decision-Ready Data','Give teams dashboards and reports that reflect real operations.')]
}
}

for key,d in pages.items():
    cards=''.join(f'<article class="social-service-card social-reveal"><span class="social-card-number">{i:02d}</span><span class="social-card-icon">{icon}</span><h3>{title}</h3><p>{desc}</p><small>{tag}</small></article>' for i,(title,desc,tag) in enumerate(d['cards'],1) for icon in ['✦' if i%3==1 else '◌' if i%3==2 else '⌁'])
    tools=''.join(f'<span>{x}</span>' for x in d['tools'])
    listing=''.join(f'<article><h3>{a}</h3><p>{b}</p></article>' for a,b in d['list'])
    steps=''.join(f'<article class="social-process-card social-reveal"><span>{i:02d}</span><h3>{a}</h3><p>{b}</p></article>' for i,(a,b) in enumerate(d['steps'],1))
    stats=''.join(f'<article><strong>{a}</strong><span>{b}</span></article>' for a,b in d['stats'])
    faqs=''.join(f'<details class="social-faq-item social-reveal" {"open" if i==0 else ""}><summary>{q}</summary><p>{a}</p></details>' for i,(q,a) in enumerate(d['faqs']))
    benefits=''.join(f'<article class="social-benefit-card social-reveal"><span>{i:02d}</span><h3>{a}</h3><p>{b}</p></article>' for i,(a,b) in enumerate(d['benefits'],1))
    active=f'href="#{d["hash"]}" class="is-active"'
    # replace first matching active by injecting a marked active menu separately
    nav=menu.replace(f'href="#{d["hash"]}"',active)
    html=f'''export const {key}Content = `
{header(key)}
<section class="social-detail-hero social-reveal service-variant-hero">
  <div class="social-hero-glow social-hero-glow-orange"></div><div class="social-hero-glow social-hero-glow-blue"></div><div class="social-hero-grid"></div>
  <div class="social-hero-inner"><p class="social-kicker">THE BUZZ MEDIA · {d['kicker']}</p><h1>{d['hero']}</h1><div class="social-hero-meta"><p>{d['intro']}</p><a href="#detail-services">Explore services <span>↘</span></a></div></div>
</section>
<div class="service-marquee social-detail-marquee"><div class="service-marquee-track"><span>{d['name'].upper()}</span><b>✦</b><span>STRATEGY</span><b>✦</b><span>DESIGN</span><b>✦</b><span>TECHNOLOGY</span><b>✦</b><span>GROWTH</span><b>✦</b><span>{d['name'].upper()}</span><b>✦</b></div></div>
<section class="social-section social-intro social-reveal" id="detail-services"><div class="social-section-label"><span>01</span><em>{d['kicker']}</em></div><div class="social-intro-grid"><div><h2>{d['hero'].replace('.', '')}</h2></div><div><p>{d['intro']}</p><a href="#consultation" class="social-inline-link">Start a project <span>↗</span></a></div></div></section>
<section class="social-services-grid social-section">{cards}</section>
<section class="social-tools social-section social-reveal"><div class="social-section-label"><span>02</span><em>TOOLS &amp; ECOSYSTEM</em></div><h2>{d['ecosystem']}</h2><p>Modern tools, clear systems and practical implementation working together to create measurable digital momentum.</p><div class="social-tool-row">{tools}</div></section>
<section class="social-expertise social-section"><div class="social-section-label social-reveal"><span>03</span><em>WHY CHOOSE US</em></div><div class="social-expertise-grid"><div class="social-reveal"><h2>{d['expertise']}</h2><p class="social-muted">{d['expertcopy']}</p><div class="social-list">{listing}</div></div><div class="social-image-card social-reveal"><img src="https://images.unsplash.com/photo-1552664730-d307ca884978?auto=format&fit=crop&q=88&w=1200" alt="The Buzz Media team working on a digital project"><span>THE BUZZ MEDIA · {d['name'].upper()}</span></div></div></section>
<section class="social-process social-section"><div class="social-section-label social-reveal"><span>04</span><em>HOW IT WORKS</em></div><div class="social-process-head social-reveal"><h2>{d['process']}</h2><p>A clear process keeps strategy, execution and feedback moving together from first conversation to launch and beyond.</p></div><div class="social-process-grid">{steps}</div></section>
<section class="social-leaders social-section social-reveal"><div class="social-section-label"><span>05</span><em>WHO WE ARE</em></div><div class="social-leaders-grid"><div><h2>{d['leaders']}</h2><p>The Buzz Media combines strategy, design, technology and practical execution to help ambitious businesses build stronger digital systems.</p><a href="#contact" class="social-inline-link">Talk to us <span>↗</span></a></div><div class="social-stat-grid">{stats}</div></div></section>
<section class="social-faq social-section"><div class="social-section-label social-reveal"><span>06</span><em>FREQUENTLY ASKED QUESTIONS</em></div><div class="social-faq-head social-reveal"><h2>{d['faqtitle']}.</h2><p>Clear answers before we put the next stage of your project into motion.</p></div><div class="social-faq-grid"><div class="social-faq-list">{faqs}</div><div class="social-faq-image social-reveal"><img src="https://images.unsplash.com/photo-1556761175-b413da4baf72?auto=format&fit=crop&q=88&w=1000" alt="The Buzz Media team reviewing a project"></div></div></section>
<section class="social-benefits social-section"><div class="social-section-label social-reveal"><span>07</span><em>KEY BENEFITS</em></div><div class="social-benefits-head social-reveal"><h2>Discover the advantages of choosing The Buzz Media.</h2><p>Build a system that is useful today and ready for what comes next.</p></div><div class="social-benefit-grid">{benefits}</div></section>
<section class="social-consultation social-section social-reveal" id="consultation"><div class="social-section-label"><span>08</span><em>START A FREE CONSULTATION</em></div><h2>Start Your {d['name']} Project Today.</h2><p>Tell us what you are building and we'll map a practical next step within 24 hours.</p><form class="social-mini-form" onsubmit="return false"><input type="text" placeholder="Full Name"><input type="email" placeholder="Email"><input type="text" placeholder="Business / Brand"><input type="text" placeholder="Phone Number"><textarea placeholder="Tell us about your project..."></textarea><button type="button">Send Enquiry ↗</button></form></section>
<section class="service-cta social-detail-cta social-reveal"><p class="service-kicker">LET'S COLLABORATE</p><h2>LET'S WORK<br>TOGETHER.</h2><a href="#contact" class="service-round-cta"><span>Get In<br>Touch</span><b>↗</b></a></section>
{footer}
`;\n'''
    # replace menu generated in header with active nav variant
    html=html.replace(menu,nav)
    (root/d['file']).write_text(html)

# update existing content dropdowns to 10-item menu
for fname in ['serviceContent.js','socialMediaContent.js','performanceContent.js','seoContent.js','digitalMarketingContent.js','appDevelopmentContent.js']:
    p=root/fname
    s=p.read_text()
    import re
    s=re.sub(r'<div class="service-nav-dropdown(?: service-nav-active-wrap)?">.*?</div></div>', menu, s, count=1)
    # regex can stop at nested div; use direct between trigger and closing via exact broad non-greedy with DOTALL
    s=re.sub(r'<div class="service-nav-dropdown(?: service-nav-active-wrap)?">.*?<\/div><\/div>', menu, s, count=1, flags=re.S)
    p.write_text(s)
