export const aeoContent = `
<header class="main-header hero-header social-header"><a href="#home" class="header-logo" aria-label="The Buzz Media home"><img src="https://raw.githubusercontent.com/Ateeqqqq/thebuzzmedia-assets/refs/heads/main/logo.png-Photoroom.png" alt="The Buzz Media" class="header-logo-image" /></a><nav class="main-nav" aria-label="Main navigation"><a href="#home">Home</a><div class="service-nav-dropdown"><button class="service-dropdown-trigger" type="button">Services <span>⌄</span></button><div class="service-dropdown-menu"><a href="#performance-marketing">Performance Marketing</a><a href="#social-media-marketing">Social Media Marketing</a><a href="#seo">SEO</a><a href="#app-development">App Development</a><a href="#digital-marketing">Digital Marketing</a><a href="#website-development">Website Development</a><a href="#erp-business-software">ERP &amp; Business Software</a><a href="#graphic-designing">Graphic Designing</a><a href="#aeo" class="is-active">AEO</a><a href="#geo">GEO</a></div></div><a href="#about">About Us</a><a href="#careers">Careers</a><a href="#clients">Clients</a><a href="#contact">Contact Us</a></nav><div class="header-right"><button class="header-circle theme-button" type="button" aria-label="Theme">☾</button><a href="https://www.facebook.com/people/Thebuzzmedia/61592806665911/" target="_blank" rel="noopener noreferrer">f</a><a href="https://www.instagram.com/thebuzzmediaco/" target="_blank" rel="noopener noreferrer">◎</a><a href="https://www.linkedin.com/company/thebuzzzmedia/" target="_blank" rel="noopener noreferrer">in</a><a href="https://docs.google.com/forms/d/e/1FAIpQLScD7N0CLzOaXmmMoNnJAP18Aub78K1O5hOanYXn--QNpZVUuQ/viewform?pli=1" target="_blank" rel="noopener noreferrer">✦</a><button class="header-circle menu-button" type="button" aria-label="Menu"><span>•••</span><span>•••</span><span>•••</span></button></div></header>
<section class="social-detail-hero social-reveal service-variant-hero">
  <div class="social-hero-glow social-hero-glow-orange"></div><div class="social-hero-glow social-hero-glow-blue"></div><div class="social-hero-grid"></div>
  <div class="social-hero-inner"><p class="social-kicker">THE BUZZ MEDIA · ANSWER ENGINE OPTIMIZATION</p><h1>Dominate AI-Powered Search with <span>AEO</span> Strategies.</h1><div class="social-hero-meta"><p>Structure your brand, pages and content so answer engines can understand, trust and surface your expertise.</p><a href="#detail-services">Explore services <span>↘</span></a></div></div>
</section>
<div class="service-marquee social-detail-marquee"><div class="service-marquee-track"><span>ANSWER ENGINE OPTIMIZATION</span><b>✦</b><span>STRATEGY</span><b>✦</b><span>DESIGN</span><b>✦</b><span>TECHNOLOGY</span><b>✦</b><span>GROWTH</span><b>✦</b><span>ANSWER ENGINE OPTIMIZATION</span><b>✦</b></div></div>
<section class="social-section social-intro social-reveal" id="detail-services"><div class="social-section-label"><span>01</span><em>ANSWER ENGINE OPTIMIZATION</em></div><div class="social-intro-grid"><div><h2>Dominate AI-Powered Search with <span>AEO</span> Strategies</h2></div><div><p>Structure your brand, pages and content so answer engines can understand, trust and surface your expertise.</p><a href="#consultation" class="social-inline-link">Start a project <span>↗</span></a></div></div></section>
<section class="social-services-grid social-section"><article class="social-service-card social-reveal"><span class="social-card-number">01</span><span class="social-card-icon">✦</span><h3>AI Answer Optimization</h3><p>Make your content easy for answer engines to understand and retrieve.</p><small>AI SEARCH</small></article><article class="social-service-card social-reveal"><span class="social-card-number">02</span><span class="social-card-icon">◌</span><h3>Structured Data & Schema Markup</h3><p>Use structured signals to clarify entities, services, products and relationships.</p><small>SCHEMA</small></article><article class="social-service-card social-reveal"><span class="social-card-number">03</span><span class="social-card-icon">⌁</span><h3>Content Formatting for AI</h3><p>Create concise, well-structured answers that machines can parse and cite.</p><small>AI CONTENT</small></article><article class="social-service-card social-reveal"><span class="social-card-number">04</span><span class="social-card-icon">✦</span><h3>Featured Snippet Optimization</h3><p>Shape useful answers for prominent search result formats.</p><small>SNIPPETS</small></article><article class="social-service-card social-reveal"><span class="social-card-number">05</span><span class="social-card-icon">◌</span><h3>Authority Building</h3><p>Strengthen the trust signals around your brand, expertise and content.</p><small>AUTHORITY</small></article></section>
<section class="social-tools social-section social-reveal"><div class="social-section-label"><span>02</span><em>TOOLS &amp; ECOSYSTEM</em></div><h2>The AEO Visibility Stack</h2><p>Modern tools, clear systems and practical implementation working together to create measurable digital momentum.</p><div class="social-tool-row"><span>Google Search</span><span>Google Business Profile</span><span>Schema.org</span><span>Search Console</span><span>Bing Webmaster Tools</span><span>GA4</span><span>FAQ Schema</span><span>Organization Schema</span></div></section>
<section class="social-expertise social-section"><div class="social-section-label social-reveal"><span>03</span><em>WHY CHOOSE US</em></div><div class="social-expertise-grid"><div class="social-reveal"><h2>Mastering Answer Engine Optimization.</h2><p class="social-muted">AEO connects technical structure, useful content and authority signals so your brand can become easier for answer systems to understand and reference.</p><div class="social-list"><article><h3>Proven Expertise</h3><p>Content and structure designed around how answer engines retrieve information.</p></article><article><h3>AI-First Approach</h3><p>We format useful answers around intent, entities and clear supporting context.</p></article><article><h3>Comprehensive Services</h3><p>Technical, content and authority work combined into one discoverability system.</p></article></div></div><div class="social-image-card social-reveal"><img src="https://images.unsplash.com/photo-1552664730-d307ca884978?auto=format&fit=crop&q=88&w=1200" alt="The Buzz Media team working on a digital project"><span>THE BUZZ MEDIA · ANSWER ENGINE OPTIMIZATION</span></div></div></section>
<section class="social-process social-section"><div class="social-section-label social-reveal"><span>04</span><em>HOW IT WORKS</em></div><div class="social-process-head social-reveal"><h2>Our proven AEO process.</h2><p>A clear process keeps strategy, execution and feedback moving together from first conversation to launch and beyond.</p></div><div class="social-process-grid"><article class="social-process-card social-reveal"><span>01</span><h3>Audit</h3><p>Review technical, content and entity signals.</p></article><article class="social-process-card social-reveal"><span>02</span><h3>Structure</h3><p>Build clear information architecture and schema.</p></article><article class="social-process-card social-reveal"><span>03</span><h3>Answer</h3><p>Create useful, concise content around real questions.</p></article><article class="social-process-card social-reveal"><span>04</span><h3>Measure</h3><p>Track visibility, citations and search behavior.</p></article></div></section>
<section class="social-leaders social-section social-reveal"><div class="social-section-label"><span>05</span><em>WHO WE ARE</em></div><div class="social-leaders-grid"><div><h2>Leaders in Answer Engine Optimization.</h2><p>The Buzz Media combines strategy, design, technology and practical execution to help ambitious businesses build stronger digital systems.</p><a href="#contact" class="social-inline-link">Talk to us <span>↗</span></a></div><div class="social-stat-grid"><article><strong>93+</strong><span>CORE PAGES OPTIMIZED</span></article><article><strong>37+</strong><span>STRUCTURED CLIENTS</span></article><article><strong>24/7</strong><span>DISCOVERABILITY MINDSET</span></article></div></div></section>
<section class="social-faq social-section"><div class="social-section-label social-reveal"><span>06</span><em>FREQUENTLY ASKED QUESTIONS</em></div><div class="social-faq-head social-reveal"><h2>Everything You Need to Know About AEO.</h2><p>Clear answers before we put the next stage of your project into motion.</p></div><div class="social-faq-grid"><div class="social-faq-list"><details class="social-faq-item social-reveal" open><summary>What is Answer Engine Optimization?</summary><p>AEO is the practice of structuring content so answer engines can understand and surface useful responses.</p></details><details class="social-faq-item social-reveal" ><summary>How can AEO help increase online visibility?</summary><p>Clear answers, strong entities and structured data can improve how your information is interpreted and discovered.</p></details><details class="social-faq-item social-reveal" ><summary>What are the key elements of AEO?</summary><p>Useful content, semantic structure, schema, entity clarity, authority and technical accessibility.</p></details><details class="social-faq-item social-reveal" ><summary>How long does it take to see results with AEO?</summary><p>Results vary by site authority, competition, content quality and implementation depth.</p></details><details class="social-faq-item social-reveal" ><summary>Which answer engines do you optimize for?</summary><p>We can consider Google, Bing and emerging AI-powered discovery experiences.</p></details></div><div class="social-faq-image social-reveal"><img src="https://images.unsplash.com/photo-1556761175-b413da4baf72?auto=format&fit=crop&q=88&w=1000" alt="The Buzz Media team reviewing a project"></div></div></section>
<section class="social-benefits social-section"><div class="social-section-label social-reveal"><span>07</span><em>KEY BENEFITS</em></div><div class="social-benefits-head social-reveal"><h2>Discover the advantages of choosing The Buzz Media.</h2><p>Build a system that is useful today and ready for what comes next.</p></div><div class="social-benefit-grid"><article class="social-benefit-card social-reveal"><span>01</span><h3>AI Answer Visibility</h3><p>Make important information easier for answer systems to find.</p></article><article class="social-benefit-card social-reveal"><span>02</span><h3>Brand Authority</h3><p>Strengthen the signals around your expertise.</p></article><article class="social-benefit-card social-reveal"><span>03</span><h3>Increased Discovery</h3><p>Improve how your brand appears across modern search journeys.</p></article><article class="social-benefit-card social-reveal"><span>04</span><h3>Competitive Edge</h3><p>Prepare your content for changing search behavior.</p></article></div></section>
<section class="social-consultation social-section social-reveal" id="consultation"><div class="social-section-label"><span>08</span><em>START A FREE CONSULTATION</em></div><h2>Start Your Answer Engine Optimization Project Today.</h2><p>Tell us what you are building and we'll map a practical next step within 24 hours.</p><form class="social-mini-form" onsubmit="return false"><input type="text" placeholder="Full Name"><input type="email" placeholder="Email"><input type="text" placeholder="Business / Brand"><input type="text" placeholder="Phone Number"><textarea placeholder="Tell us about your project..."></textarea><button type="button">Send Enquiry ↗</button></form></section>
<section class="service-cta social-detail-cta social-reveal"><p class="service-kicker">LET'S COLLABORATE</p><h2>LET'S WORK<br>TOGETHER.</h2><a href="#contact" class="service-round-cta"><span>Get In<br>Touch</span><b>↗</b></a></section>
<footer class="about-footer service-footer social-footer premium-footer">
  <div class="premium-footer-top">
    <div class="premium-footer-brand">
      <a class="premium-footer-logo" href="#home" aria-label="The Buzz Media home"><span class="premium-footer-logo-mark">TB</span><span class="premium-footer-logo-name">THE BUZZ <b>MEDIA</b></span></a>
      <p>The Buzz Media is a full-service digital marketing agency building brands through strategy, design, technology, marketing and AI.</p>
      <div class="premium-footer-contact">
        <a href="tel:+919182041323"><span>↗</span> +91 9182041323</a>
        <a href="mailto:hello.thebuzzmedia@gmail.com"><span>↗</span> hello.thebuzzmedia@gmail.com</a>
      </div>
    </div>
    <div class="premium-footer-column">
      <span class="premium-footer-label">SERVICES</span>
      <a href="#digital-marketing">Digital Marketing</a>
      <a href="#performance-marketing">Performance Marketing</a>
      <a href="#social-media-marketing">Social Media Marketing</a>
      <a href="#seo">SEO</a>
      <a href="#aeo">AEO</a>
      <a href="#geo">GEO</a>
    </div>
    <div class="premium-footer-column">
      <span class="premium-footer-label">DEVELOPMENT</span>
      <a href="#website-development">Website Development</a>
      <a href="#app-development">App Development</a>
      <a href="#erp-business-software">ERP &amp; Business Software</a>
      <a href="#graphic-designing">Graphic Designing</a>
      <a href="#contact">Start a Project</a>
      <a href="#about">About Us</a>
    </div>
    <div class="premium-footer-map">
      <span class="premium-footer-label">HYDERABAD STUDIO</span>
      <iframe title="The Buzz Media location" src="https://www.google.com/maps?q=Pillar%20No.%20209%2C%20MQ%20Splendor%2C%20Upperpally%2C%20Hyderabad%2C%20Telangana%20500048&output=embed" loading="lazy" referrerpolicy="no-referrer-when-downgrade"></iframe>
    </div>
  </div>
  <div class="premium-footer-bottom">
    <span>© 2026 The Buzz Media. All rights reserved.</span>
    <div><a href="#home">Home</a><a href="#services">Services</a><a href="#contact">Contact</a></div>
    <span>Hyderabad, India</span>
  </div>
</footer>
`;
