export const digitalMarketingContent = `
<header class="main-header hero-header social-header">
  <a href="#home" class="header-logo" aria-label="The Buzz Media home"><img src="https://raw.githubusercontent.com/Ateeqqqq/thebuzzmedia-assets/refs/heads/main/logo.png-Photoroom.png" alt="The Buzz Media" class="header-logo-image" /></a>
  <nav class="main-nav" aria-label="Main navigation">
    <a href="#home">Home</a>
    <div class="service-nav-dropdown"><button class="service-dropdown-trigger" type="button">Services <span>⌄</span></button><div class="service-dropdown-menu"><a href="#performance-marketing">Performance Marketing</a><a href="#social-media-marketing">Social Media Marketing</a><a href="#seo">SEO</a><a href="#app-development">App Development</a><a href="#digital-marketing">Digital Marketing</a><a href="#website-development">Website Development</a><a href="#erp-business-software">ERP &amp; Business Software</a><a href="#graphic-designing">Graphic Designing</a><a href="#aeo">AEO</a><a href="#geo">GEO</a></div></div>
    <a href="#about">About Us</a><a href="#careers">Careers</a><a href="#clients">Clients</a><a href="#contact">Contact Us</a>
  </nav>
  <div class="header-right">
    <button class="header-circle theme-button" type="button" aria-label="Theme">☾</button>
    <a href="https://www.facebook.com/people/Thebuzzmedia/61592806665911/" target="_blank" rel="noopener noreferrer" aria-label="Facebook">f</a>
    <a href="https://www.instagram.com/thebuzzmediaco/" target="_blank" rel="noopener noreferrer" aria-label="Instagram">◎</a>
    <a href="https://www.linkedin.com/company/thebuzzzmedia/" target="_blank" rel="noopener noreferrer" aria-label="LinkedIn">in</a>
    <a href="https://docs.google.com/forms/d/e/1FAIpQLScD7N0CLzOaXmmMoNnJAP18Aub78K1O5hOanYXn--QNpZVUuQ/viewform?pli=1" target="_blank" rel="noopener noreferrer" aria-label="Join Us">✦</a>
    <button class="header-circle menu-button" type="button" aria-label="Menu"><span>•••</span><span>•••</span><span>•••</span></button>
  </div>
</header>
<section class="social-detail-hero social-reveal service-variant-hero">
  <div class="social-hero-glow social-hero-glow-orange"></div><div class="social-hero-glow social-hero-glow-blue"></div><div class="social-hero-grid"></div>
  <div class="social-hero-inner">
    <p class="social-kicker">THE BUZZ MEDIA · DIGITAL MARKETING</p>
    <h1>Accelerate Your Business with <span>Digital Marketing.</span></h1>
    <div class="social-hero-meta"><p>Build an integrated digital marketing system that connects paid media, social, search, content and conversion into one clear growth strategy.</p><a href="#detail-services">Explore services <span>↘</span></a></div>
  </div>
</section>
<div class="service-marquee social-detail-marquee"><div class="service-marquee-track"><span>DIGITAL MARKETING</span><b>✦</b><span>360° DIGITAL MARKETING SERVICES</span><b>✦</b><span>PERFORMANCE MARKETING</span><b>✦</b><span>SEO & LOCAL LISTINGS</span><b>✦</b><span>SOCIAL MEDIA MARKETING</span><b>✦</b><span>DIGITAL MARKETING</span><b>✦</b></div></div>
<section class="social-section social-intro social-reveal" id="detail-services">
  <div class="social-section-label"><span>01</span><em>DIGITAL MARKETING</em></div>
  <div class="social-intro-grid"><div><h2>Build an integrated digital marketing system that connects paid media, social, search, content and conversion into one clear growth strategy <span>with The Buzz Media.</span></h2></div><div><p>Build an integrated digital marketing system that connects paid media, social, search, content and conversion into one clear growth strategy.</p><a href="#consultation" class="social-inline-link">Build my strategy <span>↗</span></a></div></div>
</section>
<section class="social-services-grid social-section"><article class="social-service-card social-reveal"><span class="social-card-number">01</span><span class="social-card-icon">✦</span><h3>360° Digital Marketing Services</h3><p>Bring channels together under one measurable strategy covering awareness, acquisition, conversion and retention.</p><small>FULL-FUNNEL</small></article><article class="social-service-card social-reveal"><span class="social-card-number">02</span><span class="social-card-icon">↗</span><h3>Performance Marketing</h3><p>Use paid campaigns to create qualified demand and turn attention into measurable action.</p><small>PAID MEDIA</small></article><article class="social-service-card social-reveal"><span class="social-card-number">03</span><span class="social-card-icon">⌖</span><h3>SEO & Local Listings</h3><p>Grow discoverability with search optimization and local presence management.</p><small>SEARCH · LOCAL</small></article><article class="social-service-card social-reveal"><span class="social-card-number">04</span><span class="social-card-icon">◎</span><h3>Social Media Marketing</h3><p>Build a recognizable social presence through strategy, content, community and paid distribution.</p><small>SOCIAL · CONTENT</small></article><article class="social-service-card social-reveal"><span class="social-card-number">05</span><span class="social-card-icon">◌</span><h3>Retargeting Strategies</h3><p>Reconnect with high-intent visitors and move them closer to conversion with smarter sequences.</p><small>RETARGETING</small></article><article class="social-service-card social-reveal"><span class="social-card-number">06</span><span class="social-card-icon">▣</span><h3>Content Marketing</h3><p>Create useful, persuasive content that builds authority, trust and long-term demand.</p><small>CONTENT · BRAND</small></article></section>
<section class="social-tools social-section social-reveal">
  <div class="social-section-label"><span>02</span><em>TOOLS &amp; ECOSYSTEM</em></div><h2>Explore our digital marketing ecosystem.</h2><p>The right channel mix depends on your audience, offer and goals. We build the stack around what can actually move the business.</p><div class="social-tool-row"><span>Google Ads</span><span>Meta Ads</span><span>Instagram</span><span>LinkedIn</span><span>Google Analytics</span><span>Search Console</span><span>Canva</span><span>Looker Studio</span><span>HubSpot</span></div>
</section>
<section class="social-expertise social-section">
  <div class="social-section-label social-reveal"><span>03</span><em>WHY CHOOSE US</em></div>
  <div class="social-expertise-grid"><div class="social-reveal"><h2>Expertise for your Digital Marketing Success.</h2><p class="social-muted">We connect channels instead of treating them as separate islands. Strategy, creative and measurement work together around the customer journey.</p><div class="social-list"><article><h3>Proven Expertise</h3><p>Integrated campaigns that connect awareness, traffic, leads and conversion.</p></article><article><h3>Tailored Strategies</h3><p>Channel mix and messaging shaped around your market, budget and goals.</p></article><article><h3>Data-Driven Insights</h3><p>Performance signals across channels reveal where to invest and where to improve.</p></article></div></div>
  <div class="social-image-card social-reveal"><img src="https://images.unsplash.com/photo-1552664730-d307ca884978?auto=format&fit=crop&q=88&w=1200" alt="The Buzz Media team working on a digital project"><span>THE BUZZ MEDIA · DIGITAL MARKETING</span></div></div>
</section>
<section class="social-process social-section">
  <div class="social-section-label social-reveal"><span>04</span><em>HOW IT WORKS</em></div>
  <div class="social-process-head social-reveal"><h2>Our proven process for digital growth.</h2><p>We map the journey, choose the right channels and build a system that gets smarter with every cycle.</p></div><div class="social-process-grid"><article class="social-process-card social-reveal"><span>01</span><h3>Discover</h3><p>Understand audience, positioning, funnel and growth constraints.</p></article><article class="social-process-card social-reveal"><span>02</span><h3>Plan</h3><p>Build the channel mix, messaging and measurement framework.</p></article><article class="social-process-card social-reveal"><span>03</span><h3>Launch</h3><p>Activate campaigns, content and conversion touchpoints.</p></article><article class="social-process-card social-reveal"><span>04</span><h3>Optimize</h3><p>Learn from the data and improve the entire journey.</p></article></div>
</section>
<section class="social-leaders social-section social-reveal">
  <div class="social-section-label"><span>05</span><em>WHO WE ARE</em></div>
  <div class="social-leaders-grid"><div><h2>Leaders in Digital Marketing.</h2><p>The Buzz Media creates practical digital systems that combine creative communication with measurable growth across the channels that matter.</p><a href="#contact" class="social-inline-link">Talk to us <span>↗</span></a></div><div class="social-stat-grid"><article><strong>39+</strong><span>DIGITAL CAMPAIGNS</span></article><article><strong>16+</strong><span>MARKETING CHANNELS</span></article><article><strong>150+</strong><span>OPTIMIZED ASSETS</span></article></div></div>
</section>
<section class="social-faq social-section">
  <div class="social-section-label social-reveal"><span>06</span><em>FREQUENTLY ASKED QUESTIONS</em></div>
  <div class="social-faq-head social-reveal"><h2>Everything you need to know about Digital Marketing.</h2><p>Understand the channels, timelines and decisions that shape a strong digital marketing system.</p></div>
  <div class="social-faq-grid"><div class="social-faq-list"><details class="social-faq-item social-reveal" open><summary>What digital marketing services do you offer?</summary><p>We combine performance marketing, social media, SEO, content, retargeting and conversion-focused digital strategy.</p></details><details class="social-faq-item social-reveal" ><summary>How do you measure digital marketing success?</summary><p>We define KPIs around your objectives, then connect channel metrics to leads, sales, engagement and other meaningful outcomes.</p></details><details class="social-faq-item social-reveal" ><summary>How do you create a digital marketing strategy?</summary><p>We start with audience, offer, funnel and competitive context, then choose the channels and messages that fit.</p></details><details class="social-faq-item social-reveal" ><summary>What is performance marketing?</summary><p>Performance marketing uses measurable campaigns and optimization to drive specific actions such as leads, sales or enquiries.</p></details><details class="social-faq-item social-reveal" ><summary>How much do digital marketing services cost?</summary><p>Pricing depends on channels, scope, creative volume, media management and business goals. We can shape the engagement around your needs.</p></details></div><div class="social-faq-image social-reveal"><img src="https://images.unsplash.com/photo-1556761175-b413da4baf72?auto=format&fit=crop&q=88&w=1000" alt="The Buzz Media team reviewing a project"></div></div>
</section>
<section class="social-benefits social-section">
  <div class="social-section-label social-reveal"><span>07</span><em>KEY BENEFITS</em></div>
  <div class="social-benefits-head social-reveal"><h2>Discover the advantages of choosing The Buzz Media for Digital Marketing.</h2><p>One connected strategy, clearer reporting and a stronger customer journey across the digital ecosystem.</p></div><div class="social-benefit-grid"><article class="social-benefit-card social-reveal"><span>01</span><h3>Tailored Strategy</h3><p>A channel mix built around your market and commercial objectives.</p></article><article class="social-benefit-card social-reveal"><span>02</span><h3>Engaging Content</h3><p>Creative that keeps the brand recognizable across touchpoints.</p></article><article class="social-benefit-card social-reveal"><span>03</span><h3>Data-Driven Campaigns</h3><p>Decisions grounded in performance rather than guesswork.</p></article><article class="social-benefit-card social-reveal"><span>04</span><h3>Continuous Support</h3><p>Ongoing optimization as your audience and market evolve.</p></article></div>
</section>
<section class="social-consultation social-section social-reveal" id="consultation">
  <div class="social-section-label"><span>08</span><em>START A FREE CONSULTATION</em></div><h2>Start Your Digital Marketing Today.</h2><p>Tell us about your goals and we'll map a practical next step within 24 hours.</p>
  <form class="social-mini-form" onsubmit="return false"><input type="text" placeholder="Full Name" aria-label="Full Name"><input type="email" placeholder="Email" aria-label="Email"><input type="text" placeholder="Business / Brand" aria-label="Business / Brand"><input type="text" placeholder="Phone Number" aria-label="Phone Number"><textarea placeholder="Tell us about your project..." aria-label="Project details"></textarea><button type="button">Send Enquiry ↗</button></form>
</section>
<section class="service-cta social-detail-cta social-reveal"><p class="service-kicker">LET'S COLLABORATE</p><h2>LET'S WORK<br>TOGETHER.</h2><a href="#contact" class="service-round-cta"><span>Get In<br>Touch</span><b>↗</b></a></section>
<footer class="about-footer service-footer social-footer">
  <div class="about-footer-brand"><img src="https://raw.githubusercontent.com/Ateeqqqq/thebuzzmedia-assets/refs/heads/main/logo.png-Photoroom.png" alt="The Buzz Media"><p>Digital experiences, marketing systems, software and AI solutions for ambitious brands.</p><a href="tel:+919182041323">+91 91820 41323</a><a href="mailto:hello.thebuzzmedia@gmail.com">hello.thebuzzmedia@gmail.com</a></div>
  <div class="about-footer-map"><iframe title="The Buzz Media location" src="https://www.google.com/maps?q=Pillar%20No.%20209%2C%20MQ%20Splendor%2C%20Upperpally%2C%20Hyderabad%2C%20Telangana%20500048&output=embed" loading="lazy" referrerpolicy="no-referrer-when-downgrade"></iframe></div>
  <div class="about-footer-bottom"><span>© 2026 The Buzz Media. All rights reserved.</span><span>Hyderabad, India</span></div>
</footer>
`;
