export const erpbizContent = `
<header class="main-header hero-header social-header"><a href="#home" class="header-logo" aria-label="The Buzz Media home"><img src="https://raw.githubusercontent.com/Ateeqqqq/thebuzzmedia-assets/refs/heads/main/logo.png-Photoroom.png" alt="The Buzz Media" class="header-logo-image" /></a><nav class="main-nav" aria-label="Main navigation"><a href="#home">Home</a><div class="service-nav-dropdown"><button class="service-dropdown-trigger" type="button">Services <span>⌄</span></button><div class="service-dropdown-menu"><a href="#performance-marketing">Performance Marketing</a><a href="#social-media-marketing">Social Media Marketing</a><a href="#seo">SEO</a><a href="#app-development">App Development</a><a href="#digital-marketing">Digital Marketing</a><a href="#website-development">Website Development</a><a href="#erp-business-software" class="is-active">ERP &amp; Business Software</a><a href="#graphic-designing">Graphic Designing</a><a href="#aeo">AEO</a><a href="#geo">GEO</a></div></div><a href="#about">About Us</a><a href="#careers">Careers</a><a href="#clients">Clients</a><a href="#contact">Contact Us</a></nav><div class="header-right"><button class="header-circle theme-button" type="button" aria-label="Theme">☾</button><a href="https://www.facebook.com/people/Thebuzzmedia/61592806665911/" target="_blank" rel="noopener noreferrer">f</a><a href="https://www.instagram.com/thebuzzmediaco/" target="_blank" rel="noopener noreferrer">◎</a><a href="https://www.linkedin.com/company/thebuzzzmedia/" target="_blank" rel="noopener noreferrer">in</a><a href="https://docs.google.com/forms/d/e/1FAIpQLScD7N0CLzOaXmmMoNnJAP18Aub78K1O5hOanYXn--QNpZVUuQ/viewform?pli=1" target="_blank" rel="noopener noreferrer">✦</a><button class="header-circle menu-button" type="button" aria-label="Menu"><span>•••</span><span>•••</span><span>•••</span></button></div></header>
<section class="social-detail-hero social-reveal service-variant-hero">
  <div class="social-hero-glow social-hero-glow-orange"></div><div class="social-hero-glow social-hero-glow-blue"></div><div class="social-hero-grid"></div>
  <div class="social-hero-inner"><p class="social-kicker">THE BUZZ MEDIA · ERP & BUSINESS SOFTWARE</p><h1>Connect Your Business with <span>ERP & Custom Software</span>.</h1><div class="social-hero-meta"><p>Replace disconnected spreadsheets and manual handoffs with software that connects inventory, sales, purchasing, operations, teams and reporting.</p><a href="#detail-services">Explore services <span>↘</span></a></div></div>
</section>
<div class="service-marquee social-detail-marquee"><div class="service-marquee-track"><span>ERP & BUSINESS SOFTWARE</span><b>✦</b><span>STRATEGY</span><b>✦</b><span>DESIGN</span><b>✦</b><span>TECHNOLOGY</span><b>✦</b><span>GROWTH</span><b>✦</b><span>ERP & BUSINESS SOFTWARE</span><b>✦</b></div></div>
<section class="social-section social-intro social-reveal" id="detail-services"><div class="social-section-label"><span>01</span><em>ERP & BUSINESS SOFTWARE</em></div><div class="social-intro-grid"><div><h2>Connect Your Business with <span>ERP & Custom Software</span></h2></div><div><p>Replace disconnected spreadsheets and manual handoffs with software that connects inventory, sales, purchasing, operations, teams and reporting.</p><a href="#consultation" class="social-inline-link">Start a project <span>↗</span></a></div></div></section>
<section class="social-services-grid social-section"><article class="social-service-card social-reveal"><span class="social-card-number">01</span><span class="social-card-icon">✦</span><h3>ERP Development</h3><p>Design a central system for inventory, purchasing, sales, finance and operations.</p><small>ERP SYSTEMS</small></article><article class="social-service-card social-reveal"><span class="social-card-number">02</span><span class="social-card-icon">◌</span><h3>Inventory & Stock Management</h3><p>Track branch-wise stock, transfers, variants, reservations and movement in real time.</p><small>INVENTORY</small></article><article class="social-service-card social-reveal"><span class="social-card-number">03</span><span class="social-card-icon">⌁</span><h3>Sales & Order Workflows</h3><p>Connect quotation, confirmation, reservation, purchasing, delivery and payment flows.</p><small>SALES OPS</small></article><article class="social-service-card social-reveal"><span class="social-card-number">04</span><span class="social-card-icon">✦</span><h3>Custom Business Software</h3><p>Build internal tools, portals and workflows around the way your business actually operates.</p><small>CUSTOM SOFTWARE</small></article><article class="social-service-card social-reveal"><span class="social-card-number">05</span><span class="social-card-icon">◌</span><h3>Dashboards & Reporting</h3><p>Turn operational data into role-based dashboards and actionable reports.</p><small>ANALYTICS</small></article><article class="social-service-card social-reveal"><span class="social-card-number">06</span><span class="social-card-icon">⌁</span><h3>Automation & Integrations</h3><p>Connect WhatsApp, payments, courier tools, accounting systems and APIs to reduce manual work.</p><small>AUTOMATION</small></article></section>
<section class="social-tools social-section social-reveal"><div class="social-section-label"><span>02</span><em>TOOLS &amp; ECOSYSTEM</em></div><h2>The Business Systems Stack</h2><p>Modern tools, clear systems and practical implementation working together to create measurable digital momentum.</p><div class="social-tool-row"><span>React</span><span>FastAPI</span><span>PostgreSQL</span><span>MySQL</span><span>REST APIs</span><span>WhatsApp API</span><span>Razorpay</span><span>Cloud Hosting</span><span>Role-Based Access</span></div></section>
<section class="social-expertise social-section"><div class="social-section-label social-reveal"><span>03</span><em>WHY CHOOSE US</em></div><div class="social-expertise-grid"><div class="social-reveal"><h2>Business Software Built Around Your Workflow.</h2><p class="social-muted">Instead of forcing your operation into a generic product, we map your real workflow first and then design the software around the people, data and decisions that keep the business moving.</p><div class="social-list"><article><h3>Workflow-First Discovery</h3><p>We map branches, roles, stock, approvals, documents and handoffs before development.</p></article><article><h3>Modular Architecture</h3><p>Start with the workflows that matter most and expand the system as the business grows.</p></article><article><h3>Real-Time Visibility</h3><p>Give owners and teams one reliable view of operations, inventory and performance.</p></article></div></div><div class="social-image-card social-reveal"><img src="https://images.unsplash.com/photo-1552664730-d307ca884978?auto=format&fit=crop&q=88&w=1200" alt="The Buzz Media team working on a digital project"><span>THE BUZZ MEDIA · ERP & BUSINESS SOFTWARE</span></div></div></section>
<section class="social-process social-section"><div class="social-section-label social-reveal"><span>04</span><em>HOW IT WORKS</em></div><div class="social-process-head social-reveal"><h2>Our proven software process.</h2><p>A clear process keeps strategy, execution and feedback moving together from first conversation to launch and beyond.</p></div><div class="social-process-grid"><article class="social-process-card social-reveal"><span>01</span><h3>Map</h3><p>Document workflows, roles, data and exceptions.</p></article><article class="social-process-card social-reveal"><span>02</span><h3>Architect</h3><p>Design the database, modules, permissions and integrations.</p></article><article class="social-process-card social-reveal"><span>03</span><h3>Build</h3><p>Develop the web/mobile interfaces and business logic.</p></article><article class="social-process-card social-reveal"><span>04</span><h3>Deploy</h3><p>Test, train, launch and continuously improve the system.</p></article></div></section>
<section class="social-leaders social-section social-reveal"><div class="social-section-label"><span>05</span><em>WHO WE ARE</em></div><div class="social-leaders-grid"><div><h2>Software That Understands Your Business.</h2><p>The Buzz Media combines strategy, design, technology and practical execution to help ambitious businesses build stronger digital systems.</p><a href="#contact" class="social-inline-link">Talk to us <span>↗</span></a></div><div class="social-stat-grid"><article><strong>1</strong><span>CENTRAL PLATFORM</span></article><article><strong>24/7</strong><span>DATA ACCESS</span></article><article><strong>100%</strong><span>WORKFLOW FOCUS</span></article></div></div></section>
<section class="social-faq social-section"><div class="social-section-label social-reveal"><span>06</span><em>FREQUENTLY ASKED QUESTIONS</em></div><div class="social-faq-head social-reveal"><h2>Everything You Need to Know About ERP & Business Software.</h2><p>Clear answers before we put the next stage of your project into motion.</p></div><div class="social-faq-grid"><div class="social-faq-list"><details class="social-faq-item social-reveal" open><summary>Can you build a custom ERP for our business?</summary><p>Yes. We can design modules around your actual inventory, sales, purchasing, operations and reporting workflows.</p></details><details class="social-faq-item social-reveal" ><summary>Can ERP support multiple branches?</summary><p>Yes. Branch-wise roles, stock, transfers and reporting can be designed into the system.</p></details><details class="social-faq-item social-reveal" ><summary>Can you integrate existing tools?</summary><p>Yes. APIs can connect payments, messaging, courier services, accounting tools and other systems.</p></details><details class="social-faq-item social-reveal" ><summary>Can you build a mobile app with the ERP?</summary><p>Yes. A web application and Android/mobile experience can share the same central database and business logic.</p></details><details class="social-faq-item social-reveal" ><summary>How do you price custom software?</summary><p>Pricing depends on modules, integrations, user roles, mobile requirements and project complexity.</p></details></div><div class="social-faq-image social-reveal"><img src="https://images.unsplash.com/photo-1556761175-b413da4baf72?auto=format&fit=crop&q=88&w=1000" alt="The Buzz Media team reviewing a project"></div></div></section>
<section class="social-benefits social-section"><div class="social-section-label social-reveal"><span>07</span><em>KEY BENEFITS</em></div><div class="social-benefits-head social-reveal"><h2>Discover the advantages of choosing The Buzz Media.</h2><p>Build a system that is useful today and ready for what comes next.</p></div><div class="social-benefit-grid"><article class="social-benefit-card social-reveal"><span>01</span><h3>One Source of Truth</h3><p>Centralize operational data instead of scattered spreadsheets.</p></article><article class="social-benefit-card social-reveal"><span>02</span><h3>Workflow Automation</h3><p>Reduce repetitive manual work and approval delays.</p></article><article class="social-benefit-card social-reveal"><span>03</span><h3>Scalable Architecture</h3><p>Start focused and add modules as the business grows.</p></article><article class="social-benefit-card social-reveal"><span>04</span><h3>Decision-Ready Data</h3><p>Give teams dashboards and reports that reflect real operations.</p></article></div></section>
<section class="social-consultation social-section social-reveal" id="consultation"><div class="social-section-label"><span>08</span><em>START A FREE CONSULTATION</em></div><h2>Start Your ERP & Business Software Project Today.</h2><p>Tell us what you are building and we'll map a practical next step within 24 hours.</p><form class="social-mini-form" onsubmit="return false"><input type="text" placeholder="Full Name"><input type="email" placeholder="Email"><input type="text" placeholder="Business / Brand"><input type="text" placeholder="Phone Number"><textarea placeholder="Tell us about your project..."></textarea><button type="button">Send Enquiry ↗</button></form></section>
<section class="service-cta social-detail-cta social-reveal"><p class="service-kicker">LET'S COLLABORATE</p><h2>LET'S WORK<br>TOGETHER.</h2><a href="#contact" class="service-round-cta"><span>Get In<br>Touch</span><b>↗</b></a></section>
<footer class="about-footer service-footer social-footer premium-footer">
  <div class="premium-footer-top">
    <div class="premium-footer-brand">
      <a class="premium-footer-logo" href="#home" aria-label="The Buzz Media home"><span class="premium-footer-logo-mark">TB</span><span class="premium-footer-logo-name">THE BUZZ <b>MEDIA</b></span></a>
      <p>The Buzz Media is a full-service digital marketing agency building brands through strategy, design, technology, marketing and AI.</p>
      <div class="premium-footer-contact"><a href="tel:+919182041323"><span>↗</span> +91 9182041323</a><a href="mailto:hello.thebuzzmedia@gmail.com"><span>↗</span> hello.thebuzzmedia@gmail.com</a></div>
    </div>
    <div class="premium-footer-column"><span class="premium-footer-label">SERVICES</span><a href="#digital-marketing">Digital Marketing</a><a href="#performance-marketing">Performance Marketing</a><a href="#social-media-marketing">Social Media Marketing</a><a href="#seo">SEO</a><a href="#aeo">AEO</a><a href="#geo">GEO</a></div>
    <div class="premium-footer-column"><span class="premium-footer-label">DEVELOPMENT</span><a href="#website-development">Website Development</a><a href="#app-development">App Development</a><a href="#erp-business-software">ERP &amp; Business Software</a><a href="#graphic-designing">Graphic Designing</a><a href="#about">About Us</a><a href="#contact">Start a Project</a></div>
    <div class="premium-footer-map"><span class="premium-footer-label">HYDERABAD STUDIO</span><iframe title="The Buzz Media location" src="https://www.google.com/maps?q=Pillar%20No.%20209%2C%20MQ%20Splendor%2C%20Upperpally%2C%20Hyderabad%2C%20Telangana%20500048&output=embed" loading="lazy" referrerpolicy="no-referrer-when-downgrade"></iframe></div>
  </div>
  <div class="premium-footer-bottom"><span>© 2026 The Buzz Media. All rights reserved.</span><div><a href="#home">Home</a><a href="#services">Services</a><a href="#about">About</a><a href="#contact">Contact</a></div><span>Hyderabad, India</span></div>
</footer>
`;
