export const graphicContent = `
<header class="main-header hero-header social-header"><a href="#home" class="header-logo" aria-label="The Buzz Media home"><img src="https://raw.githubusercontent.com/Ateeqqqq/thebuzzmedia-assets/refs/heads/main/logo.png-Photoroom.png" alt="The Buzz Media" class="header-logo-image" /></a><nav class="main-nav" aria-label="Main navigation"><a href="#home">Home</a><div class="service-nav-dropdown"><button class="service-dropdown-trigger" type="button">Services <span>⌄</span></button><div class="service-dropdown-menu"><a href="#performance-marketing">Performance Marketing</a><a href="#social-media-marketing">Social Media Marketing</a><a href="#seo">SEO</a><a href="#app-development">App Development</a><a href="#digital-marketing">Digital Marketing</a><a href="#website-development">Website Development</a><a href="#erp-business-software">ERP &amp; Business Software</a><a href="#graphic-designing" class="is-active">Graphic Designing</a><a href="#aeo">AEO</a><a href="#geo">GEO</a></div></div><a href="#about">About Us</a><a href="#careers">Careers</a><a href="#clients">Clients</a><a href="#contact">Contact Us</a></nav><div class="header-right"><button class="header-circle theme-button" type="button" aria-label="Theme">☾</button><a href="https://www.facebook.com/people/Thebuzzmedia/61592806665911/" target="_blank" rel="noopener noreferrer">f</a><a href="https://www.instagram.com/thebuzzmediaco/" target="_blank" rel="noopener noreferrer">◎</a><a href="https://www.linkedin.com/company/thebuzzzmedia/" target="_blank" rel="noopener noreferrer">in</a><a href="https://docs.google.com/forms/d/e/1FAIpQLScD7N0CLzOaXmmMoNnJAP18Aub78K1O5hOanYXn--QNpZVUuQ/viewform?pli=1" target="_blank" rel="noopener noreferrer">✦</a><button class="header-circle menu-button" type="button" aria-label="Menu"><span>•••</span><span>•••</span><span>•••</span></button></div></header>
<section class="social-detail-hero social-reveal service-variant-hero">
  <div class="social-hero-glow social-hero-glow-orange"></div><div class="social-hero-glow social-hero-glow-blue"></div><div class="social-hero-grid"></div>
  <div class="social-hero-inner"><p class="social-kicker">THE BUZZ MEDIA · GRAPHICS & CONTENT DESIGN</p><h1>Elevate Your Brand with <span>Graphic Design</span>.</h1><div class="social-hero-meta"><p>Turn your visual identity into a consistent, recognizable brand system with design that works across every touchpoint.</p><a href="#detail-services">Explore services <span>↘</span></a></div></div>
</section>
<div class="service-marquee social-detail-marquee"><div class="service-marquee-track"><span>GRAPHICS & CONTENT</span><b>✦</b><span>STRATEGY</span><b>✦</b><span>DESIGN</span><b>✦</b><span>TECHNOLOGY</span><b>✦</b><span>GROWTH</span><b>✦</b><span>GRAPHICS & CONTENT</span><b>✦</b></div></div>
<section class="social-section social-intro social-reveal" id="detail-services"><div class="social-section-label"><span>01</span><em>GRAPHICS & CONTENT DESIGN</em></div><div class="social-intro-grid"><div><h2>Elevate Your Brand with <span>Graphic Design</span></h2></div><div><p>Turn your visual identity into a consistent, recognizable brand system with design that works across every touchpoint.</p><a href="#consultation" class="social-inline-link">Start a project <span>↗</span></a></div></div></section>
<section class="social-services-grid social-section"><article class="social-service-card social-reveal"><span class="social-card-number">01</span><span class="social-card-icon">✦</span><h3>Graphic Design</h3><p>Create striking visuals that capture your brand identity and communicate clearly.</p><small>VISUAL IDENTITY</small></article><article class="social-service-card social-reveal"><span class="social-card-number">02</span><span class="social-card-icon">◌</span><h3>Content Writing</h3><p>Develop high-quality copy and content that gives your brand a sharper voice.</p><small>CONTENT</small></article><article class="social-service-card social-reveal"><span class="social-card-number">03</span><span class="social-card-icon">⌁</span><h3>Branding Solutions</h3><p>Build a cohesive brand identity through professional logos and strategic creative direction.</p><small>BRANDING</small></article><article class="social-service-card social-reveal"><span class="social-card-number">04</span><span class="social-card-icon">✦</span><h3>Visual Storytelling</h3><p>Combine design and narrative to make campaigns memorable and engaging.</p><small>CAMPAIGNS</small></article><article class="social-service-card social-reveal"><span class="social-card-number">05</span><span class="social-card-icon">◌</span><h3>SEO Content Optimization</h3><p>Make content useful, readable and discoverable across search and AI discovery.</p><small>CONTENT SEO</small></article></section>
<section class="social-tools graphics-tools-reference social-section social-reveal">
  <div class="social-section-label"><span>02</span><em>TOOLS WE USE</em></div>
  <h2>Explore Our Graphics &amp; Content Tool Stack</h2>
  <p>The creative stack we use to build polished visual identities, content systems and campaign assets.</p>
  <div class="graphics-tool-category"><h3>Graphic Design Tools</h3><div class="graphics-tool-list"><span>Adobe Photoshop</span><span>Adobe Illustrator</span><span>Figma</span><span>Canva</span></div></div>
  <div class="graphics-tool-category"><h3>Content Writing Tools</h3><div class="graphics-tool-list"><span>Grammarly</span><span>Hemingway Editor</span><span>Copy.ai</span><span>Surfer SEO</span></div></div>
  <div class="graphics-tool-category"><h3>Collaboration &amp; Workflow Tools</h3><div class="graphics-tool-list"><span>Trello</span><span>Asana</span><span>Monday.com</span><span>Planable</span></div></div>
</section>
<section class="social-expertise social-section"><div class="social-section-label social-reveal"><span>03</span><em>WHY CHOOSE US</em></div><div class="social-expertise-grid"><div class="social-reveal"><h2>Expertise for your Graphics & Content Success.</h2><p class="social-muted">We combine visual craft, brand thinking and content strategy to create a consistent system your audience can recognize and remember.</p><div class="social-list"><article><h3>Experienced Designers</h3><p>Purposeful visual systems built around your brand personality and audience.</p></article><article><h3>Consistent Content</h3><p>Clear creative direction across social, web, campaigns and everyday communication.</p></article><article><h3>Creativity Meets Strategy</h3><p>Design choices tied to business goals, not decoration for decoration’s sake.</p></article></div></div><div class="social-image-card social-reveal"><img src="https://images.unsplash.com/photo-1552664730-d307ca884978?auto=format&fit=crop&q=88&w=1200" alt="The Buzz Media team working on a digital project"><span>THE BUZZ MEDIA · GRAPHICS & CONTENT</span></div></div></section>
<section class="social-process social-section"><div class="social-section-label social-reveal"><span>04</span><em>HOW IT WORKS</em></div><div class="social-process-head social-reveal"><h2>Our proven process for creative work.</h2><p>A clear process keeps strategy, execution and feedback moving together from first conversation to launch and beyond.</p></div><div class="social-process-grid"><article class="social-process-card social-reveal"><span>01</span><h3>Discover</h3><p>Understand the brand, audience and creative challenge.</p></article><article class="social-process-card social-reveal"><span>02</span><h3>Concept</h3><p>Develop directions, references and a visual route.</p></article><article class="social-process-card social-reveal"><span>03</span><h3>Create</h3><p>Design the assets, content and system with consistency.</p></article><article class="social-process-card social-reveal"><span>04</span><h3>Refine</h3><p>Review, test and prepare everything for launch.</p></article></div></section>
<section class="social-leaders social-section social-reveal"><div class="social-section-label"><span>05</span><em>WHO WE ARE</em></div><div class="social-leaders-grid"><div><h2>Leaders in Graphics & Content.</h2><p>The Buzz Media combines strategy, design, technology and practical execution to help ambitious businesses build stronger digital systems.</p><a href="#contact" class="social-inline-link">Talk to us <span>↗</span></a></div><div class="social-stat-grid"><article><strong>70+</strong><span>CREATIVE PROJECTS</span></article><article><strong>8+</strong><span>BRAND SYSTEMS</span></article><article><strong>142+</strong><span>DESIGN ASSETS</span></article></div></div></section>
<section class="social-faq social-section"><div class="social-section-label social-reveal"><span>06</span><em>FREQUENTLY ASKED QUESTIONS</em></div><div class="social-faq-head social-reveal"><h2>Everything You Need to Know About Graphics & Content.</h2><p>Clear answers before we put the next stage of your project into motion.</p></div><div class="social-faq-grid"><div class="social-faq-list"><details class="social-faq-item social-reveal" open><summary>What types of graphics do you create?</summary><p>Social posts, campaign creatives, brand assets, presentations, web visuals and more.</p></details><details class="social-faq-item social-reveal" ><summary>Do you offer content writing services?</summary><p>Yes. We can develop brand-aligned copy for websites, campaigns and social content.</p></details><details class="social-faq-item social-reveal" ><summary>Can you help develop a content strategy?</summary><p>Yes. We can map content pillars, formats and creative direction around your goals.</p></details><details class="social-faq-item social-reveal" ><summary>What is your process for graphic design projects?</summary><p>We move from discovery and concept to design, review and final delivery.</p></details><details class="social-faq-item social-reveal" ><summary>How much does graphic design cost?</summary><p>Pricing depends on scope, quantity, complexity and turnaround time.</p></details></div><div class="social-faq-image social-reveal"><img src="https://images.unsplash.com/photo-1556761175-b413da4baf72?auto=format&fit=crop&q=88&w=1000" alt="The Buzz Media team reviewing a project"></div></div></section>
<section class="social-benefits social-section"><div class="social-section-label social-reveal"><span>07</span><em>KEY BENEFITS</em></div><div class="social-benefits-head social-reveal"><h2>Discover the advantages of choosing The Buzz Media.</h2><p>Build a system that is useful today and ready for what comes next.</p></div><div class="social-benefit-grid"><article class="social-benefit-card social-reveal"><span>01</span><h3>Custom Visuals</h3><p>Purpose-built creative that fits your brand and audience.</p></article><article class="social-benefit-card social-reveal"><span>02</span><h3>Compelling Content</h3><p>Clear messaging paired with visual consistency.</p></article><article class="social-benefit-card social-reveal"><span>03</span><h3>SEO-Optimized Content</h3><p>Content designed for readability and discoverability.</p></article><article class="social-benefit-card social-reveal"><span>04</span><h3>Continuous Support</h3><p>Ongoing creative support as your brand grows.</p></article></div></section>
<section class="social-consultation social-section social-reveal" id="consultation"><div class="social-section-label"><span>08</span><em>START A FREE CONSULTATION</em></div><h2>Start Your Graphics & Content Project Today.</h2><p>Tell us what you are building and we'll map a practical next step within 24 hours.</p><form class="social-mini-form" onsubmit="return false"><input type="text" placeholder="Full Name"><input type="email" placeholder="Email"><input type="text" placeholder="Business / Brand"><input type="text" placeholder="Phone Number"><textarea placeholder="Tell us about your project..."></textarea><button type="button">Send Enquiry ↗</button></form></section>
<section class="service-cta social-detail-cta social-reveal"><p class="service-kicker">LET'S COLLABORATE</p><h2>LET'S WORK<br>TOGETHER.</h2><a href="#contact" class="service-round-cta"><span>Get In<br>Touch</span><b>↗</b></a></section>
<footer class="about-footer service-footer social-footer premium-footer">
  <div class="premium-footer-top">
    <div class="premium-footer-brand">
      <a class="premium-footer-logo" href="#home" aria-label="The Buzz Media home"><span class="premium-footer-logo-mark">TB</span><span class="premium-footer-logo-name">THE BUZZ <b>MEDIA</b></span></a>
      <p>The Buzz Media is a full-service digital marketing agency building brands through strategy, design, technology, marketing and AI.</p>
      <div class="premium-footer-contact">
        <a href="tel:+919182041323"><span>↗</span> +91 9182041323</a>
        <a href="mailto:hello.thebuzzmedia@gmail.com"><span>↗</span> hello.thebuzzmedia@gmail.com</a>
      </div>
    </div>
    <div class="premium-footer-column">
      <span class="premium-footer-label">SERVICES</span>
      <a href="#digital-marketing">Digital Marketing</a>
      <a href="#performance-marketing">Performance Marketing</a>
      <a href="#social-media-marketing">Social Media Marketing</a>
      <a href="#seo">SEO</a>
      <a href="#aeo">AEO</a>
      <a href="#geo">GEO</a>
    </div>
    <div class="premium-footer-column">
      <span class="premium-footer-label">DEVELOPMENT</span>
      <a href="#website-development">Website Development</a>
      <a href="#app-development">App Development</a>
      <a href="#erp-business-software">ERP &amp; Business Software</a>
      <a href="#graphic-designing">Graphic Designing</a>
      <a href="#contact">Start a Project</a>
      <a href="#about">About Us</a>
    </div>
    <div class="premium-footer-map">
      <span class="premium-footer-label">HYDERABAD STUDIO</span>
      <iframe title="The Buzz Media location" src="https://www.google.com/maps?q=Pillar%20No.%20209%2C%20MQ%20Splendor%2C%20Upperpally%2C%20Hyderabad%2C%20Telangana%20500048&output=embed" loading="lazy" referrerpolicy="no-referrer-when-downgrade"></iframe>
    </div>
  </div>
  <div class="premium-footer-bottom">
    <span>© 2026 The Buzz Media. All rights reserved.</span>
    <div><a href="#home">Home</a><a href="#services">Services</a><a href="#contact">Contact</a></div>
    <span>Hyderabad, India</span>
  </div>
</footer>
`;
