export const performanceContent = `
<header class="main-header hero-header social-header">
  <a href="#home" class="header-logo" aria-label="The Buzz Media home"><img src="https://raw.githubusercontent.com/Ateeqqqq/thebuzzmedia-assets/refs/heads/main/logo.png-Photoroom.png" alt="The Buzz Media" class="header-logo-image" /></a>
  <nav class="main-nav" aria-label="Main navigation">
    <a href="#home">Home</a>
    <div class="service-nav-dropdown"><button class="service-dropdown-trigger" type="button">Services <span>⌄</span></button><div class="service-dropdown-menu"><a href="#performance-marketing">Performance Marketing</a><a href="#social-media-marketing">Social Media Marketing</a><a href="#seo">SEO</a><a href="#app-development">App Development</a><a href="#digital-marketing">Digital Marketing</a><a href="#website-development">Website Development</a><a href="#erp-business-software">ERP &amp; Business Software</a><a href="#graphic-designing">Graphic Designing</a><a href="#aeo">AEO</a><a href="#geo">GEO</a></div></div>
    <a href="#about">About Us</a><a href="#careers">Careers</a><a href="#clients">Clients</a><a href="#contact">Contact Us</a>
  </nav>
  <div class="header-right">
    <button class="header-circle theme-button" type="button" aria-label="Theme">☾</button>
    <a href="https://www.facebook.com/people/Thebuzzmedia/61592806665911/" target="_blank" rel="noopener noreferrer" aria-label="Facebook">f</a>
    <a href="https://www.instagram.com/thebuzzmediaco/" target="_blank" rel="noopener noreferrer" aria-label="Instagram">◎</a>
    <a href="https://www.linkedin.com/company/thebuzzzmedia/" target="_blank" rel="noopener noreferrer" aria-label="LinkedIn">in</a>
    <a href="https://docs.google.com/forms/d/e/1FAIpQLScD7N0CLzOaXmmMoNnJAP18Aub78K1O5hOanYXn--QNpZVUuQ/viewform?pli=1" target="_blank" rel="noopener noreferrer" aria-label="Join Us">✦</a>
    <button class="header-circle menu-button" type="button" aria-label="Menu"><span>•••</span><span>•••</span><span>•••</span></button>
  </div>
</header>
<section class="social-detail-hero social-reveal service-variant-hero">
  <div class="social-hero-glow social-hero-glow-orange"></div><div class="social-hero-glow social-hero-glow-blue"></div><div class="social-hero-grid"></div>
  <div class="social-hero-inner">
    <p class="social-kicker">THE BUZZ MEDIA · PERFORMANCE MARKETING</p>
    <h1>Accelerate Your Business Growth with <span>Performance Marketing.</span></h1>
    <div class="social-hero-meta"><p>Turn paid media into a predictable growth engine with strategy, creative testing, precise targeting and conversion-focused optimization across the channels that matter.</p><a href="#detail-services">Explore services <span>↘</span></a></div>
  </div>
</section>
<div class="service-marquee social-detail-marquee"><div class="service-marquee-track"><span>PERFORMANCE MARKETING</span><b>✦</b><span>META & PAID SOCIAL</span><b>✦</b><span>GOOGLE ADS</span><b>✦</b><span>YOUTUBE ADS</span><b>✦</b><span>CONVERSION RATE OPTIMIZATION</span><b>✦</b><span>PERFORMANCE MARKETING</span><b>✦</b></div></div>
<section class="social-section social-intro social-reveal" id="detail-services">
  <div class="social-section-label"><span>01</span><em>PERFORMANCE MARKETING</em></div>
  <div class="social-intro-grid"><div><h2>Turn paid media into a predictable growth engine with strategy, creative testing, precise targeting and conversion-focused optimization across the channels that matter <span>with The Buzz Media.</span></h2></div><div><p>Turn paid media into a predictable growth engine with strategy, creative testing, precise targeting and conversion-focused optimization across the channels that matter.</p><a href="#consultation" class="social-inline-link">Build my strategy <span>↗</span></a></div></div>
</section>
<section class="social-services-grid social-section"><article class="social-service-card social-reveal"><span class="social-card-number">01</span><span class="social-card-icon">∞</span><h3>Meta & Paid Social</h3><p>Build high-intent campaigns across Meta with audience architecture, creative testing and conversion tracking.</p><small>PAID SOCIAL</small></article><article class="social-service-card social-reveal"><span class="social-card-number">02</span><span class="social-card-icon">⌕</span><h3>Google Ads</h3><p>Capture active demand with Search, Performance Max and high-intent campaigns built around profitable outcomes.</p><small>SEARCH ADS</small></article><article class="social-service-card social-reveal"><span class="social-card-number">03</span><span class="social-card-icon">▶</span><h3>YouTube Ads</h3><p>Reach the right audiences with video campaigns designed for awareness, consideration and measurable action.</p><small>VIDEO ADS</small></article><article class="social-service-card social-reveal"><span class="social-card-number">04</span><span class="social-card-icon">↗</span><h3>Conversion Rate Optimization</h3><p>Remove friction from landing pages and funnels so more qualified clicks become enquiries, purchases and leads.</p><small>CRO · FUNNELS</small></article><article class="social-service-card social-reveal"><span class="social-card-number">05</span><span class="social-card-icon">◌</span><h3>Performance Analytics</h3><p>Turn campaign data into decisions with clear reporting, attribution and continuous optimization.</p><small>DATA · ROAS</small></article></section>
<section class="social-tools social-section social-reveal">
  <div class="social-section-label"><span>02</span><em>TOOLS &amp; ECOSYSTEM</em></div><h2>The performance stack behind smarter growth.</h2><p>We connect media buying, analytics, creative testing and conversion systems so every rupee has a job.</p><div class="social-tool-row"><span>Meta Ads</span><span>Google Ads</span><span>GA4</span><span>GTM</span><span>Looker Studio</span><span>Search Console</span><span>Hotjar</span><span>Microsoft Clarity</span></div>
</section>
<section class="social-expertise social-section">
  <div class="social-section-label social-reveal"><span>03</span><em>WHY CHOOSE US</em></div>
  <div class="social-expertise-grid"><div class="social-reveal"><h2>Expertise for your Performance Success.</h2><p class="social-muted">Our performance team blends media buying with creative and conversion thinking, giving campaigns a tighter feedback loop from click to customer.</p><div class="social-list"><article><h3>Proven Expertise</h3><p>Campaign structures designed around acquisition economics, not vanity metrics.</p></article><article><h3>Custom Strategy</h3><p>Audiences, offers, creatives and landing journeys shaped around your business.</p></article><article><h3>ROI-Focused Approach</h3><p>Budget decisions are guided by conversion quality, efficiency and scalable growth.</p></article></div></div>
  <div class="social-image-card social-reveal"><img src="https://images.unsplash.com/photo-1552664730-d307ca884978?auto=format&fit=crop&q=88&w=1200" alt="The Buzz Media team working on a digital project"><span>THE BUZZ MEDIA · PERFORMANCE MARKETING</span></div></div>
</section>
<section class="social-process social-section">
  <div class="social-section-label social-reveal"><span>04</span><em>HOW IT WORKS</em></div>
  <div class="social-process-head social-reveal"><h2>Our proven process for performance growth.</h2><p>A disciplined cycle of research, launch, measurement and optimization keeps campaigns moving forward.</p></div><div class="social-process-grid"><article class="social-process-card social-reveal"><span>01</span><h3>Research</h3><p>Understand the market, audience, offer and economics.</p></article><article class="social-process-card social-reveal"><span>02</span><h3>Launch</h3><p>Build campaigns, tracking and creative variations with clean structure.</p></article><article class="social-process-card social-reveal"><span>03</span><h3>Optimize</h3><p>Read performance signals and improve bids, audiences and creative.</p></article><article class="social-process-card social-reveal"><span>04</span><h3>Scale</h3><p>Shift budget toward proven winners while protecting efficiency.</p></article></div>
</section>
<section class="social-leaders social-section social-reveal">
  <div class="social-section-label"><span>05</span><em>WHO WE ARE</em></div>
  <div class="social-leaders-grid"><div><h2>Leaders in Performance Marketing.</h2><p>The Buzz Media builds measurable acquisition systems that connect paid traffic with stronger creative, sharper funnels and commercial outcomes.</p><a href="#contact" class="social-inline-link">Talk to us <span>↗</span></a></div><div class="social-stat-grid"><article><strong>286+</strong><span>PERFORMANCE CAMPAIGNS</span></article><article><strong>7+</strong><span>PLATFORMS & CHANNELS</span></article><article><strong>200+</strong><span>GLOBAL CLIENTS</span></article></div></div>
</section>
<section class="social-faq social-section">
  <div class="social-section-label social-reveal"><span>06</span><em>FREQUENTLY ASKED QUESTIONS</em></div>
  <div class="social-faq-head social-reveal"><h2>Everything you need to know about Performance Marketing.</h2><p>Clear answers before we put your paid growth engine into motion.</p></div>
  <div class="social-faq-grid"><div class="social-faq-list"><details class="social-faq-item social-reveal" open><summary>What platforms do you use for performance marketing?</summary><p>We work across Meta, Google, YouTube and other channels where your audience and economics make sense.</p></details><details class="social-faq-item social-reveal" ><summary>How do you measure campaign success?</summary><p>We focus on qualified leads, conversions, acquisition cost, return on ad spend and the metrics tied to your actual business goals.</p></details><details class="social-faq-item social-reveal" ><summary>Can you manage an existing campaign?</summary><p>Yes. We can audit an existing setup, identify leakage and rebuild or optimize what is already working.</p></details><details class="social-faq-item social-reveal" ><summary>How quickly can campaigns launch?</summary><p>After access, tracking and creative requirements are confirmed, initial campaigns can be prepared quickly with a clear launch plan.</p></details><details class="social-faq-item social-reveal" ><summary>Do you create ad creatives?</summary><p>Yes. We can develop performance-focused creative concepts, copy and variations for testing.</p></details></div><div class="social-faq-image social-reveal"><img src="https://images.unsplash.com/photo-1556761175-b413da4baf72?auto=format&fit=crop&q=88&w=1000" alt="The Buzz Media team reviewing a project"></div></div>
</section>
<section class="social-benefits social-section">
  <div class="social-section-label social-reveal"><span>07</span><em>KEY BENEFITS</em></div>
  <div class="social-benefits-head social-reveal"><h2>Discover the advantages of choosing The Buzz Media for Performance Marketing.</h2><p>Build a paid acquisition system that learns quickly, spends intelligently and improves over time.</p></div><div class="social-benefit-grid"><article class="social-benefit-card social-reveal"><span>01</span><h3>Tailored Campaigns</h3><p>Campaign structures designed around your audience, offer and conversion goal.</p></article><article class="social-benefit-card social-reveal"><span>02</span><h3>Targeted Ads</h3><p>Precise audience and creative testing to find efficient pockets of demand.</p></article><article class="social-benefit-card social-reveal"><span>03</span><h3>Data-Driven Optimization</h3><p>Continuous analysis turns campaign signals into smarter decisions.</p></article><article class="social-benefit-card social-reveal"><span>04</span><h3>Ongoing Optimization</h3><p>We keep testing, refining and scaling instead of letting campaigns go stale.</p></article></div>
</section>
<section class="social-consultation social-section social-reveal" id="consultation">
  <div class="social-section-label"><span>08</span><em>START A FREE CONSULTATION</em></div><h2>Start Your Performance Growth Today.</h2><p>Tell us about your goals and we'll map a practical next step within 24 hours.</p>
  <form class="social-mini-form" onsubmit="return false"><input type="text" placeholder="Full Name" aria-label="Full Name"><input type="email" placeholder="Email" aria-label="Email"><input type="text" placeholder="Business / Brand" aria-label="Business / Brand"><input type="text" placeholder="Phone Number" aria-label="Phone Number"><textarea placeholder="Tell us about your project..." aria-label="Project details"></textarea><button type="button">Send Enquiry ↗</button></form>
</section>
<section class="service-cta social-detail-cta social-reveal"><p class="service-kicker">LET'S COLLABORATE</p><h2>LET'S WORK<br>TOGETHER.</h2><a href="#contact" class="service-round-cta"><span>Get In<br>Touch</span><b>↗</b></a></section>
<footer class="about-footer service-footer social-footer">
  <div class="about-footer-brand"><img src="https://raw.githubusercontent.com/Ateeqqqq/thebuzzmedia-assets/refs/heads/main/logo.png-Photoroom.png" alt="The Buzz Media"><p>Digital experiences, marketing systems, software and AI solutions for ambitious brands.</p><a href="tel:+919182041323">+91 91820 41323</a><a href="mailto:hello.thebuzzmedia@gmail.com">hello.thebuzzmedia@gmail.com</a></div>
  <div class="about-footer-map"><iframe title="The Buzz Media location" src="https://www.google.com/maps?q=Pillar%20No.%20209%2C%20MQ%20Splendor%2C%20Upperpally%2C%20Hyderabad%2C%20Telangana%20500048&output=embed" loading="lazy" referrerpolicy="no-referrer-when-downgrade"></iframe></div>
  <div class="about-footer-bottom"><span>© 2026 The Buzz Media. All rights reserved.</span><span>Hyderabad, India</span></div>
</footer>
`;
