export const seoContent = `
<header class="main-header hero-header social-header">
  <a href="#home" class="header-logo" aria-label="The Buzz Media home"><img src="https://raw.githubusercontent.com/Ateeqqqq/thebuzzmedia-assets/refs/heads/main/logo.png-Photoroom.png" alt="The Buzz Media" class="header-logo-image" /></a>
  <nav class="main-nav" aria-label="Main navigation">
    <a href="#home">Home</a>
    <div class="service-nav-dropdown"><button class="service-dropdown-trigger" type="button">Services <span>⌄</span></button><div class="service-dropdown-menu"><a href="#performance-marketing">Performance Marketing</a><a href="#social-media-marketing">Social Media Marketing</a><a href="#seo">SEO</a><a href="#app-development">App Development</a><a href="#digital-marketing">Digital Marketing</a><a href="#website-development">Website Development</a><a href="#erp-business-software">ERP &amp; Business Software</a><a href="#graphic-designing">Graphic Designing</a><a href="#aeo">AEO</a><a href="#geo">GEO</a></div></div>
    <a href="#about">About Us</a><a href="#careers">Careers</a><a href="#clients">Clients</a><a href="#contact">Contact Us</a>
  </nav>
  <div class="header-right">
    <button class="header-circle theme-button" type="button" aria-label="Theme">☾</button>
    <a href="https://www.facebook.com/people/Thebuzzmedia/61592806665911/" target="_blank" rel="noopener noreferrer" aria-label="Facebook">f</a>
    <a href="https://www.instagram.com/thebuzzmediaco/" target="_blank" rel="noopener noreferrer" aria-label="Instagram">◎</a>
    <a href="https://www.linkedin.com/company/thebuzzzmedia/" target="_blank" rel="noopener noreferrer" aria-label="LinkedIn">in</a>
    <a href="https://docs.google.com/forms/d/e/1FAIpQLScD7N0CLzOaXmmMoNnJAP18Aub78K1O5hOanYXn--QNpZVUuQ/viewform?pli=1" target="_blank" rel="noopener noreferrer" aria-label="Join Us">✦</a>
    <button class="header-circle menu-button" type="button" aria-label="Menu"><span>•••</span><span>•••</span><span>•••</span></button>
  </div>
</header>
<section class="social-detail-hero social-reveal service-variant-hero">
  <div class="social-hero-glow social-hero-glow-orange"></div><div class="social-hero-glow social-hero-glow-blue"></div><div class="social-hero-grid"></div>
  <div class="social-hero-inner">
    <p class="social-kicker">THE BUZZ MEDIA · SEO</p>
    <h1>Transform Your Online Visibility with <span>SEO.</span></h1>
    <div class="social-hero-meta"><p>Build durable organic visibility with technical SEO, content strategy, local search and modern optimization designed to bring qualified people to your business.</p><a href="#detail-services">Explore services <span>↘</span></a></div>
  </div>
</section>
<div class="service-marquee social-detail-marquee"><div class="service-marquee-track"><span>SEO</span><b>✦</b><span>ON-PAGE SEO</span><b>✦</b><span>OFF-PAGE SEO</span><b>✦</b><span>LOCAL SEO</span><b>✦</b><span>TECHNICAL SEO</span><b>✦</b><span>SEO</span><b>✦</b></div></div>
<section class="social-section social-intro social-reveal" id="detail-services">
  <div class="social-section-label"><span>01</span><em>SEO</em></div>
  <div class="social-intro-grid"><div><h2>Build durable organic visibility with technical SEO, content strategy, local search and modern optimization designed to bring qualified people to your business <span>with The Buzz Media.</span></h2></div><div><p>Build durable organic visibility with technical SEO, content strategy, local search and modern optimization designed to bring qualified people to your business.</p><a href="#consultation" class="social-inline-link">Build my strategy <span>↗</span></a></div></div>
</section>
<section class="social-services-grid social-section"><article class="social-service-card social-reveal"><span class="social-card-number">01</span><span class="social-card-icon">⌁</span><h3>On-Page SEO</h3><p>Improve content, metadata, internal linking and page structure around real search intent.</p><small>ON-PAGE SEO</small></article><article class="social-service-card social-reveal"><span class="social-card-number">02</span><span class="social-card-icon">↗</span><h3>Off-Page SEO</h3><p>Strengthen authority through credible digital signals, relevant mentions and strategic outreach.</p><small>OFF-PAGE SEO</small></article><article class="social-service-card social-reveal"><span class="social-card-number">03</span><span class="social-card-icon">⌖</span><h3>Local SEO</h3><p>Own high-intent local searches with optimized profiles, location pages and local relevance.</p><small>LOCAL SEO</small></article><article class="social-service-card social-reveal"><span class="social-card-number">04</span><span class="social-card-icon">⚙</span><h3>Technical SEO</h3><p>Fix crawlability, indexation, performance and architecture issues that hold search visibility back.</p><small>TECHNICAL SEO</small></article><article class="social-service-card social-reveal"><span class="social-card-number">05</span><span class="social-card-icon">▣</span><h3>E-Commerce SEO</h3><p>Build category, product and collection structures that help online stores capture demand.</p><small>E-COMMERCE SEO</small></article><article class="social-service-card social-reveal"><span class="social-card-number">06</span><span class="social-card-icon">✦</span><h3>Content Marketing</h3><p>Create useful, search-led content that answers questions and compounds organic traffic.</p><small>CONTENT · SEARCH</small></article></section>
<section class="social-tools social-section social-reveal">
  <div class="social-section-label"><span>02</span><em>TOOLS &amp; ECOSYSTEM</em></div><h2>A connected SEO toolkit for sustainable visibility.</h2><p>From technical audits to reporting, we use a practical stack to discover opportunities and measure progress.</p><div class="social-tool-row"><span>Google Search Console</span><span>GA4</span><span>Semrush</span><span>Ahrefs</span><span>Screaming Frog</span><span>PageSpeed Insights</span><span>Looker Studio</span><span>Keyword Planner</span></div>
</section>
<section class="social-expertise social-section">
  <div class="social-section-label social-reveal"><span>03</span><em>WHY CHOOSE US</em></div>
  <div class="social-expertise-grid"><div class="social-reveal"><h2>Expertise for your SEO Success.</h2><p class="social-muted">SEO is a long game, but it should never be vague. We combine technical clarity, search intent and useful content to build compounding visibility.</p><div class="social-list"><article><h3>Technical SEO</h3><p>Clean foundations make it easier for search engines to crawl, understand and rank your site.</p></article><article><h3>Intent-Led Strategy</h3><p>We map content to the questions and commercial intent behind real searches.</p></article><article><h3>Continuous SEO Tools</h3><p>Audits, rankings, traffic and conversion data keep the roadmap grounded.</p></article></div></div>
  <div class="social-image-card social-reveal"><img src="https://images.unsplash.com/photo-1552664730-d307ca884978?auto=format&fit=crop&q=88&w=1200" alt="The Buzz Media team working on a digital project"><span>THE BUZZ MEDIA · SEO</span></div></div>
</section>
<section class="social-process social-section">
  <div class="social-section-label social-reveal"><span>04</span><em>HOW IT WORKS</em></div>
  <div class="social-process-head social-reveal"><h2>Our proven process for SEO growth.</h2><p>We turn search data into a prioritized roadmap, then improve the site in measurable iterations.</p></div><div class="social-process-grid"><article class="social-process-card social-reveal"><span>01</span><h3>Audit</h3><p>Find technical, content and authority gaps.</p></article><article class="social-process-card social-reveal"><span>02</span><h3>Map</h3><p>Build keyword, page and intent clusters around your goals.</p></article><article class="social-process-card social-reveal"><span>03</span><h3>Optimize</h3><p>Improve pages, architecture, performance and content.</p></article><article class="social-process-card social-reveal"><span>04</span><h3>Grow</h3><p>Publish, earn authority and refine based on search data.</p></article></div>
</section>
<section class="social-leaders social-section social-reveal">
  <div class="social-section-label"><span>05</span><em>WHO WE ARE</em></div>
  <div class="social-leaders-grid"><div><h2>Pioneers in Search Excellence.</h2><p>The Buzz Media combines technical SEO with content and conversion thinking so organic traffic has somewhere valuable to go.</p><a href="#contact" class="social-inline-link">Talk to us <span>↗</span></a></div><div class="social-stat-grid"><article><strong>24+</strong><span>SEO AUDITS & ROADMAPS</span></article><article><strong>32+</strong><span>ACTIVE KEYWORD SETS</span></article><article><strong>81+</strong><span>OPTIMIZED PAGES</span></article></div></div>
</section>
<section class="social-faq social-section">
  <div class="social-section-label social-reveal"><span>06</span><em>FREQUENTLY ASKED QUESTIONS</em></div>
  <div class="social-faq-head social-reveal"><h2>Everything you need to know about SEO.</h2><p>Straight answers about timelines, rankings and the work behind sustainable search growth.</p></div>
  <div class="social-faq-grid"><div class="social-faq-list"><details class="social-faq-item social-reveal" open><summary>What is SEO and why is it important?</summary><p>SEO improves how easily search engines understand your website and how relevant it appears for valuable searches.</p></details><details class="social-faq-item social-reveal" ><summary>How long does it take to see results from SEO?</summary><p>Timing varies by competition, site health, authority and scope. SEO is typically measured through progressive gains rather than one instant change.</p></details><details class="social-faq-item social-reveal" ><summary>What do you include in an SEO audit?</summary><p>We review technical health, indexation, content, internal linking, performance, search intent and key competitive opportunities.</p></details><details class="social-faq-item social-reveal" ><summary>Can you help with local SEO?</summary><p>Yes. Local SEO can include business profile optimization, location pages, reviews, citations and local content.</p></details><details class="social-faq-item social-reveal" ><summary>What makes your SEO approach different?</summary><p>We connect visibility to useful content, strong UX and business outcomes instead of chasing rankings in isolation.</p></details></div><div class="social-faq-image social-reveal"><img src="https://images.unsplash.com/photo-1556761175-b413da4baf72?auto=format&fit=crop&q=88&w=1000" alt="The Buzz Media team reviewing a project"></div></div>
</section>
<section class="social-benefits social-section">
  <div class="social-section-label social-reveal"><span>07</span><em>KEY BENEFITS</em></div>
  <div class="social-benefits-head social-reveal"><h2>Discover the advantages of choosing The Buzz Media for SEO.</h2><p>Create an organic growth system that is technically sound, useful to people and built to compound.</p></div><div class="social-benefit-grid"><article class="social-benefit-card social-reveal"><span>01</span><h3>Technical Foundations</h3><p>Fix the structural issues that prevent search engines from understanding your site.</p></article><article class="social-benefit-card social-reveal"><span>02</span><h3>Expert SEO Team</h3><p>Strategy and execution across technical, content and authority work.</p></article><article class="social-benefit-card social-reveal"><span>03</span><h3>Data-Driven Decisions</h3><p>Priorities are shaped by search demand, competition and performance.</p></article><article class="social-benefit-card social-reveal"><span>04</span><h3>24/7 Support</h3><p>Keep improving as search behavior, content and your business evolve.</p></article></div>
</section>
<section class="social-consultation social-section social-reveal" id="consultation">
  <div class="social-section-label"><span>08</span><em>START A FREE CONSULTATION</em></div><h2>Start Your SEO Growth Today.</h2><p>Tell us about your goals and we'll map a practical next step within 24 hours.</p>
  <form class="social-mini-form" onsubmit="return false"><input type="text" placeholder="Full Name" aria-label="Full Name"><input type="email" placeholder="Email" aria-label="Email"><input type="text" placeholder="Business / Brand" aria-label="Business / Brand"><input type="text" placeholder="Phone Number" aria-label="Phone Number"><textarea placeholder="Tell us about your project..." aria-label="Project details"></textarea><button type="button">Send Enquiry ↗</button></form>
</section>
<section class="service-cta social-detail-cta social-reveal"><p class="service-kicker">LET'S COLLABORATE</p><h2>LET'S WORK<br>TOGETHER.</h2><a href="#contact" class="service-round-cta"><span>Get In<br>Touch</span><b>↗</b></a></section>
<footer class="about-footer service-footer social-footer">
  <div class="about-footer-brand"><img src="https://raw.githubusercontent.com/Ateeqqqq/thebuzzmedia-assets/refs/heads/main/logo.png-Photoroom.png" alt="The Buzz Media"><p>Digital experiences, marketing systems, software and AI solutions for ambitious brands.</p><a href="tel:+919182041323">+91 91820 41323</a><a href="mailto:hello.thebuzzmedia@gmail.com">hello.thebuzzmedia@gmail.com</a></div>
  <div class="about-footer-map"><iframe title="The Buzz Media location" src="https://www.google.com/maps?q=Pillar%20No.%20209%2C%20MQ%20Splendor%2C%20Upperpally%2C%20Hyderabad%2C%20Telangana%20500048&output=embed" loading="lazy" referrerpolicy="no-referrer-when-downgrade"></iframe></div>
  <div class="about-footer-bottom"><span>© 2026 The Buzz Media. All rights reserved.</span><span>Hyderabad, India</span></div>
</footer>
`;
