export const websiteContent = `
<header class="main-header hero-header social-header"><a href="#home" class="header-logo" aria-label="The Buzz Media home"><img src="https://raw.githubusercontent.com/Ateeqqqq/thebuzzmedia-assets/refs/heads/main/logo.png-Photoroom.png" alt="The Buzz Media" class="header-logo-image" /></a><nav class="main-nav" aria-label="Main navigation"><a href="#home">Home</a><div class="service-nav-dropdown"><button class="service-dropdown-trigger" type="button">Services <span>⌄</span></button><div class="service-dropdown-menu"><a href="#performance-marketing">Performance Marketing</a><a href="#social-media-marketing">Social Media Marketing</a><a href="#seo">SEO</a><a href="#app-development">App Development</a><a href="#digital-marketing">Digital Marketing</a><a href="#website-development" class="is-active">Website Development</a><a href="#erp-business-software">ERP &amp; Business Software</a><a href="#graphic-designing">Graphic Designing</a><a href="#aeo">AEO</a><a href="#geo">GEO</a></div></div><a href="#about">About Us</a><a href="#careers">Careers</a><a href="#clients">Clients</a><a href="#contact">Contact Us</a></nav><div class="header-right"><button class="header-circle theme-button" type="button" aria-label="Theme">☾</button><a href="https://www.facebook.com/people/Thebuzzmedia/61592806665911/" target="_blank" rel="noopener noreferrer">f</a><a href="https://www.instagram.com/thebuzzmediaco/" target="_blank" rel="noopener noreferrer">◎</a><a href="https://www.linkedin.com/company/thebuzzzmedia/" target="_blank" rel="noopener noreferrer">in</a><a href="https://docs.google.com/forms/d/e/1FAIpQLScD7N0CLzOaXmmMoNnJAP18Aub78K1O5hOanYXn--QNpZVUuQ/viewform?pli=1" target="_blank" rel="noopener noreferrer">✦</a><button class="header-circle menu-button" type="button" aria-label="Menu"><span>•••</span><span>•••</span><span>•••</span></button></div></header>
<section class="social-detail-hero social-reveal service-variant-hero">
  <div class="social-hero-glow social-hero-glow-orange"></div><div class="social-hero-glow social-hero-glow-blue"></div><div class="social-hero-grid"></div>
  <div class="social-hero-inner"><p class="social-kicker">THE BUZZ MEDIA · WEB DEVELOPMENT</p><h1>Transformative Web Solutions by <span>The Buzz Media</span> to Boost Your Digital Presence.</h1><div class="social-hero-meta"><p>Build a website that is fast, responsive, conversion-ready and designed around how your customers actually move.</p><a href="#detail-services">Explore services <span>↘</span></a></div></div>
</section>
<div class="service-marquee social-detail-marquee"><div class="service-marquee-track"><span>WEBSITE DEVELOPMENT</span><b>✦</b><span>STRATEGY</span><b>✦</b><span>DESIGN</span><b>✦</b><span>TECHNOLOGY</span><b>✦</b><span>GROWTH</span><b>✦</b><span>WEBSITE DEVELOPMENT</span><b>✦</b></div></div>
<section class="social-section social-intro social-reveal" id="detail-services"><div class="social-section-label"><span>01</span><em>WEB DEVELOPMENT</em></div><div class="social-intro-grid"><div><h2>Transformative Web Solutions by <span>The Buzz Media</span> to Boost Your Digital Presence</h2></div><div><p>Build a website that is fast, responsive, conversion-ready and designed around how your customers actually move.</p><a href="#consultation" class="social-inline-link">Start a project <span>↗</span></a></div></div></section>
<section class="social-services-grid social-section"><article class="social-service-card social-reveal"><span class="social-card-number">01</span><span class="social-card-icon social-card-image-icon"><img src="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQuykldrDHRHXbUx4sXDKHV9v9aZ6Ehn8rtS4bv2mA6Uw&s=10" alt="Web development" /></span><h3>Website Design & Development</h3><p>Crafting custom websites with modern design, intuitive interfaces and responsive layouts.</p><small>WEB DESIGN</small></article><article class="social-service-card social-reveal"><span class="social-card-number">02</span><span class="social-card-icon social-card-image-icon"><img src="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQuykldrDHRHXbUx4sXDKHV9v9aZ6Ehn8rtS4bv2mA6Uw&s=10" alt="Web development" /></span><h3>E-Commerce Development</h3><p>Build high-converting commerce experiences with scalable product and checkout flows.</p><small>COMMERCE</small></article><article class="social-service-card social-reveal"><span class="social-card-number">03</span><span class="social-card-icon social-card-image-icon"><img src="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQuykldrDHRHXbUx4sXDKHV9v9aZ6Ehn8rtS4bv2mA6Uw&s=10" alt="Web development" /></span><h3>WordPress Development</h3><p>Flexible WordPress builds for brands that need control, speed and a manageable CMS.</p><small>WORDPRESS</small></article><article class="social-service-card social-reveal"><span class="social-card-number">04</span><span class="social-card-icon social-card-image-icon"><img src="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQuykldrDHRHXbUx4sXDKHV9v9aZ6Ehn8rtS4bv2mA6Uw&s=10" alt="Web development" /></span><h3>CMS Development</h3><p>Create structured content management systems that make everyday updates simple.</p><small>CMS</small></article><article class="social-service-card social-reveal"><span class="social-card-number">05</span><span class="social-card-icon social-card-image-icon"><img src="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQuykldrDHRHXbUx4sXDKHV9v9aZ6Ehn8rtS4bv2mA6Uw&s=10" alt="Web development" /></span><h3>Custom Web Application Development</h3><p>Build focused web applications for unique workflows, portals and customer experiences.</p><small>WEB APPS</small></article><article class="social-service-card social-reveal"><span class="social-card-number">06</span><span class="social-card-icon social-card-image-icon"><img src="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQuykldrDHRHXbUx4sXDKHV9v9aZ6Ehn8rtS4bv2mA6Uw&s=10" alt="Web development" /></span><h3>Website Maintenance</h3><p>Keep your website secure, current, monitored and continuously improved.</p><small>SUPPORT</small></article></section>
<section class="social-tools web-tools-reference social-section social-reveal">
  <div class="social-section-label"><span>02</span><em>TECHNOLOGIES WE USE</em></div>
  <h2>Explore Our Comprehensive Technology Stack</h2>
  <p>Modern technologies selected for performance, scalability, maintainability and real-world business requirements.</p>
  <div class="web-tech-category"><h3>Frontend Technologies</h3><div class="web-tech-list"><span>HTML5</span><span>CSS3</span><span>JavaScript</span><span>React.js</span><span>Vue.js</span><span>Angular</span></div></div>
  <div class="web-tech-category"><h3>Backend Technologies</h3><div class="web-tech-list"><span>Python</span><span>FastAPI</span><span>Django</span><span>Node.js</span><span>Express.js</span><span>Laravel</span></div></div>
  <div class="web-tech-category"><h3>Database Technologies</h3><div class="web-tech-list"><span>MySQL</span><span>MongoDB</span><span>PostgreSQL</span></div></div>
  <div class="web-tech-category"><h3>CMS Platforms</h3><div class="web-tech-list"><span>WordPress</span><span>Shopify</span><span>Magento</span><span>Elementor</span></div></div>
</section>
<section class="social-expertise social-section"><div class="social-section-label social-reveal"><span>03</span><em>WHY CHOOSE US</em></div><div class="social-expertise-grid"><div class="social-reveal"><h2>Expertise for Your Web Success.</h2><p class="social-muted">Our development process balances polished UX with reliable engineering, performance and maintainability so the website keeps working after launch.</p><div class="social-list"><article><h3>Experienced Team</h3><p>Designers and developers who work together from structure to deployment.</p></article><article><h3>Tailored Solutions</h3><p>We build around your business model, content and conversion goals.</p></article><article><h3>Cutting-Edge Technology</h3><p>Modern frameworks and tools chosen for performance, flexibility and scale.</p></article></div></div><div class="social-image-card social-reveal"><img src="https://images.unsplash.com/photo-1552664730-d307ca884978?auto=format&fit=crop&q=88&w=1200" alt="The Buzz Media team working on a digital project"><span>THE BUZZ MEDIA · WEBSITE DEVELOPMENT</span></div></div></section>
<section class="social-process social-section"><div class="social-section-label social-reveal"><span>04</span><em>HOW IT WORKS</em></div><div class="social-process-head social-reveal"><h2>Our proven process for web projects.</h2><p>A clear process keeps strategy, execution and feedback moving together from first conversation to launch and beyond.</p></div><div class="social-process-grid"><article class="social-process-card social-reveal"><span>01</span><h3>Plan</h3><p>Map pages, journeys, content and technical requirements.</p></article><article class="social-process-card social-reveal"><span>02</span><h3>Design</h3><p>Create a clear visual system and responsive interface.</p></article><article class="social-process-card social-reveal"><span>03</span><h3>Build</h3><p>Develop, integrate, test and optimize the experience.</p></article><article class="social-process-card social-reveal"><span>04</span><h3>Launch</h3><p>Deploy, monitor and support the live product.</p></article></div></section>
<section class="social-leaders social-section social-reveal"><div class="social-section-label"><span>05</span><em>WHO WE ARE</em></div><div class="social-leaders-grid"><div><h2>Leaders in Website Development.</h2><p>The Buzz Media combines strategy, design, technology and practical execution to help ambitious businesses build stronger digital systems.</p><a href="#contact" class="social-inline-link">Talk to us <span>↗</span></a></div><div class="social-stat-grid"><article><strong>120+</strong><span>DIGITAL PROJECTS</span></article><article><strong>35+</strong><span>BRANDS & CLIENTS</span></article><article><strong>5+</strong><span>YEARS OF PRACTICAL EXPERIENCE</span></article></div></div></section>
<section class="social-faq social-section"><div class="social-section-label social-reveal"><span>06</span><em>FREQUENTLY ASKED QUESTIONS</em></div><div class="social-faq-head social-reveal"><h2>Everything You Need to Know About Website Development.</h2><p>Clear answers before we put the next stage of your project into motion.</p></div><div class="social-faq-grid"><div class="social-faq-list"><details class="social-faq-item social-reveal" open><summary>What platforms do you build websites with?</summary><p>We work with React-based stacks, WordPress and custom web technologies depending on the project.</p></details><details class="social-faq-item social-reveal" ><summary>How long does it take to build a website?</summary><p>Timelines depend on scope, content, integrations and revision cycles.</p></details><details class="social-faq-item social-reveal" ><summary>Do you provide website maintenance services?</summary><p>Yes. We can provide ongoing updates, monitoring, fixes and improvements.</p></details><details class="social-faq-item social-reveal" ><summary>Can you build a custom web app?</summary><p>Yes. We can build dashboards, portals and workflow-based applications.</p></details><details class="social-faq-item social-reveal" ><summary>How much does a website cost?</summary><p>The price depends on pages, functionality, integrations and design complexity.</p></details></div><div class="social-faq-image social-reveal"><img src="https://images.unsplash.com/photo-1556761175-b413da4baf72?auto=format&fit=crop&q=88&w=1000" alt="The Buzz Media team reviewing a project"></div></div></section>
<section class="social-benefits social-section"><div class="social-section-label social-reveal"><span>07</span><em>KEY BENEFITS</em></div><div class="social-benefits-head social-reveal"><h2>Discover the advantages of choosing The Buzz Media.</h2><p>Build a system that is useful today and ready for what comes next.</p></div><div class="social-benefit-grid"><article class="social-benefit-card social-reveal"><span>01</span><h3>Custom Solutions</h3><p>Web experiences designed around your business.</p></article><article class="social-benefit-card social-reveal"><span>02</span><h3>Expert Team</h3><p>A connected design and development workflow.</p></article><article class="social-benefit-card social-reveal"><span>03</span><h3>Data-Driven Insights</h3><p>Performance and analytics built into the process.</p></article><article class="social-benefit-card social-reveal"><span>04</span><h3>Dedicated Support</h3><p>Support and improvements beyond launch.</p></article></div></section>
<section class="social-consultation social-section social-reveal" id="consultation"><div class="social-section-label"><span>08</span><em>START A FREE CONSULTATION</em></div><h2>Start Your Website Development Project Today.</h2><p>Tell us what you are building and we'll map a practical next step within 24 hours.</p><form class="social-mini-form" onsubmit="return false"><input type="text" placeholder="Full Name"><input type="email" placeholder="Email"><input type="text" placeholder="Business / Brand"><input type="text" placeholder="Phone Number"><textarea placeholder="Tell us about your project..."></textarea><button type="button">Send Enquiry ↗</button></form></section>
<section class="service-cta social-detail-cta social-reveal"><p class="service-kicker">LET'S COLLABORATE</p><h2>LET'S WORK<br>TOGETHER.</h2><a href="#contact" class="service-round-cta"><span>Get In<br>Touch</span><b>↗</b></a></section>
<footer class="about-footer service-footer social-footer premium-footer">
  <div class="premium-footer-top">
    <div class="premium-footer-brand">
      <a class="premium-footer-logo" href="#home" aria-label="The Buzz Media home"><span class="premium-footer-logo-mark">TB</span><span class="premium-footer-logo-name">THE BUZZ <b>MEDIA</b></span></a>
      <p>The Buzz Media is a full-service digital marketing agency building brands through strategy, design, technology, marketing and AI.</p>
      <div class="premium-footer-contact">
        <a href="tel:+919182041323"><span>↗</span> +91 9182041323</a>
        <a href="mailto:hello.thebuzzmedia@gmail.com"><span>↗</span> hello.thebuzzmedia@gmail.com</a>
      </div>
    </div>
    <div class="premium-footer-column">
      <span class="premium-footer-label">SERVICES</span>
      <a href="#digital-marketing">Digital Marketing</a>
      <a href="#performance-marketing">Performance Marketing</a>
      <a href="#social-media-marketing">Social Media Marketing</a>
      <a href="#seo">SEO</a>
      <a href="#aeo">AEO</a>
      <a href="#geo">GEO</a>
    </div>
    <div class="premium-footer-column">
      <span class="premium-footer-label">DEVELOPMENT</span>
      <a href="#website-development">Website Development</a>
      <a href="#app-development">App Development</a>
      <a href="#erp-business-software">ERP &amp; Business Software</a>
      <a href="#graphic-designing">Graphic Designing</a>
      <a href="#contact">Start a Project</a>
      <a href="#about">About Us</a>
    </div>
    <div class="premium-footer-map">
      <span class="premium-footer-label">HYDERABAD STUDIO</span>
      <iframe title="The Buzz Media location" src="https://www.google.com/maps?q=Pillar%20No.%20209%2C%20MQ%20Splendor%2C%20Upperpally%2C%20Hyderabad%2C%20Telangana%20500048&output=embed" loading="lazy" referrerpolicy="no-referrer-when-downgrade"></iframe>
    </div>
  </div>
  <div class="premium-footer-bottom">
    <span>© 2026 The Buzz Media. All rights reserved.</span>
    <div><a href="#home">Home</a><a href="#services">Services</a><a href="#contact">Contact</a></div>
    <span>Hyderabad, India</span>
  </div>
</footer>
`;
